### DISCUSSION TITLE
how to insert images inside the markdown

### DISCUSSION THREAD

**Discussion by evil1morty** [sveltia/sveltia-cms#151] [Q&A] [answered]
on the markdown editor can we insert images like decap cms ?

**Comment by kyoshino** [comment, marked as answer]
Currently, you need to write raw Markdown to insert images, since editor components for the [Markdown widget](https://decapcms.org/docs/widgets/#markdown) (`image`, `code-block` and custom components) are not yet supported in Sveltia CMS as mentioned in README. I’ll work on it next month. 🙂

**Reply by CarloBu** [reply]
did you check the Toast UI rich text editor? https://ui.toast.com/tui-editor
it supports images with markdown output and it is made with vanilla js. I guess the integration to the Sveltia CMS would be straightforward.

**Reply by kyoshino** [reply]
Not sure if I could use the Toast UI editor because some editors don’t support Chinese/Japanese/Korean text input well, but in Netlify/Decap CMS, inserting an image into the text editor looks like this:

https://stackoverflow.com/questions/63742357/netlify-cms-images-are-uploaded-into-wrong-media-folder

You’ll get an image selector plus the `alt` and `title` fields right out of the box. Basically, an editor component is a nested field in the text editor, and yes, it’s a [bit complicated](https://github.com/umaranis/svelte-lexical/blob/master/docs/decorator-node.md) to implement.

**Reply by kyoshino** [reply]
BTW, I have never seen/used Toast UI, but it has everything I want to do with [Sveltia UI](https://github.com/sveltia/sveltia-ui), like an enterprise-level data grid component 😆

**Reply by CarloBu** [reply]
> You’ll get an image selector plus the alt and title fields right out of the box. Basically, an editor component is a nested field in the text editor, and yes, it’s a [bit complicated](https://github.com/umaranis/svelte-lexical/blob/master/docs/decorator-node.md) to implement.

Ugh, I can't even understand the pain of integrating a React-based text editor framework into a Svelte project.

I noticed that the last update for the Toast editor was one year ago, which is not ideal. :/

Did you check out the Svelte wrapper project for Lexical?
https://github.com/umaranis/svelte-lexical
Would this be useful for your use case?

Also, another cool text editor that supports Svelte is:
https://tiptap.dev/docs/editor/examples/default

I am not sure if it supports Chinese/Japanese/Korean text input well.

Page CMS, based on Vue, uses Tiptap for its text editor, which has a nice UI.
![image](https://github.com/sveltia/sveltia-cms/assets/145860771/39422f8e-bd3d-45a5-bd95-acfd3430e99c)

**Reply by CarloBu** [reply]
`BTW, I have never seen/used Toast UI, but it has everything I want to do with [Sveltia UI](https://github.com/sveltia/sveltia-ui), like an enterprise-level data grid component 😆`

yeah, too bad the project is not maintainable anymore :/

**Reply by kyoshino** [reply]
I know Svelte Lexical but decided to [implement by myself](https://github.com/sveltia/sveltia-ui/tree/main/src/lib/components/text-editor) because 

- Svelte Lexical is not localizable
- Sveltia doesn’t need all the features
- Sveltia uses it’s own UI components, like buttons, dropdown menus, etc.
- Sveltia CMS has to implement it’s own editor components anyway, including image and code

Ohh, Toast UI Editor is no longer maintained? That’s sad. The last release is Feb 2023, and it does have Chinese/Japanese/Korean [IME issues](https://github.com/nhn/tui.editor/issues?q=is%3Aissue+is%3Aopen+IME) even though NHN is a Korean company.

The core of Lexical is vanilla JS and is maintained by Facebook, so it’s probably a safe choice.

**Reply by CarloBu** [reply]
> I know Svelte Lexical but decided to [implement by myself](https://github.com/sveltia/sveltia-ui/tree/main/src/lib/components/text-editor) because....

ok, I see. there is a reason. Thank you for the explanation, from the outside it looks like plug-and-play, but it's not. :)

> Ohh, Toast UI Editor is no longer maintained? That’s sad. The last release is Feb 2023, and it does have Chinese/Japanese/Korean [IME issues](https://github.com/nhn/tui.editor/issues?q=is%3Aissue+is%3Aopen+IME) even though NHN is a Korean company.

So it was a bad call then, sorry for the little distraction. 

> The core of Lexical is vanilla JS and is maintained by Facebook, so it’s probably a safe choice.

yeah, that's a smart move to bet on the biggest players to keep their projects going (except google :))

**Reply by RDjarbeng** [reply]
Now that Toast UI is not being maintained, is there a chance a solution to allow inserting images into markdown could be implemented anytime soon?

**Reply by kyoshino** [reply]
It’s being tracked in #156. I’ll get it done by the end of this month.

**Reply by RDjarbeng** [reply]
Okay, thanks for the update

**Reply by mike-dataduality** [reply]
> Currently, you need to write raw Markdown to insert images, since editor components for the [Markdown widget](https://decapcms.org/docs/widgets/#markdown) (`image`, `code-block` and custom components) are not yet supported in Sveltia CMS as mentioned in README. I’ll work on it next month. 🙂

What's the latest on this?

**Reply by RDjarbeng** [reply]
This was added to fix #156. It's been implemented now. You can add images in the editor, clicking from uploaded assets or uploading your own without typing markdown. 

> The wait is over! [v0.48.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.48.0) added the support for the `image` editor component.

**Reply by mike-dataduality** [reply]
> This was added to fix #156. It's been implemented now. You can add images in the editor, clicking from uploaded assets or uploading your own without typing markdown.

hmm it's not working for me. I click on add image and nothing happens :(

<img width="676" height="364" alt="image" src="https://github.com/user-attachments/assets/a40a2088-a583-4ed1-8bf5-404c6c7da79c" />



My config.yml for the products page is like this:

```
  # Products
  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Stripe Price ID", name: "stripePriceId", widget: "string", hint: "Create this in Stripe Dashboard" }
      - { label: "Available", name: "available", widget: "boolean", default: true }
      - { label: "Category", name: "category", widget: "select", options: ["Original Art", "Prints", "Digital"] }
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
```
