### DISCUSSION TITLE
How to setup my local git repository?

### DISCUSSION THREAD

**Discussion by asdromundo** [sveltia/sveltia-cms#179] [Q&A] [answered]
I'm trying to use SveltiaCMS as local using the Edge browser , but following the documentation I think that it should be asking me for the root of the directory instead of asking me to write it in the config file.

This is my config file

```yml
backend:
  name: local

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "Blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "../src/Blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
```

Without the backend lines it says that no backend is defined in the config. After adding this lines it shows:
![image](https://github.com/user-attachments/assets/0d9840d4-c8fc-4d32-9ed7-23d00f2d9169)

In no case I'm seeing an option to select a root for the directory.

I'm using Windows 11, no WSL. Tried with Brave with flag options and Edge.

**Comment by kyoshino** [comment, marked as answer]
As described in the [Decap CMS doc](https://decapcms.org/docs/github-backend/), the backend config has to be:

```yaml
backend:
  name: github # or gitlab
  repo: owner-name/repo-name # path to your repo
```


Looks like `name: local` or `name: proxy` could be used in Netlify/Decap CMS as per https://github.com/decaporg/decap-cms/issues/7217. I’ll later add compatibility for these legacy, undocumented backend names.

**Reply by asdromundo** [reply]
@kyoshino Thank you for your quick answer.  
I wasn't following the Decap CMS that you provided as they have a [separate method for a local git repository.](https://decapcms.org/docs/working-with-a-local-git-repository/)
```yaml
# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  ```
  This is not equivalent to the Sveltia CMS, as we don't have the git-gateway and DecapCMS doesn't require a `repo`. This difference is not mentioned in the [README](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#working-with-a-local-git-repository) section of local repositories. So maybe it would be worthwhile to add the example.
  
  Thank you again.
