### DISCUSSION TITLE
Can't set `media_folder` per post properly

### DISCUSSION THREAD

**Discussion by akasmix** [sveltia/sveltia-cms#190] [Q&A] [answered]
My config:

```yaml
media_folder: /static/images/
public_folder: /images

collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    create: true
    folder: content/posts
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
      - label: Title
        name: title
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
```

My content tree:

```
content
└── posts
    ├── post-1
    │   ├── index.html
    │   ├── lion.jpg
    │   └── zoo.png
    └── post-2
        ├── cover.png
        └── index.html
```

It allows me to add and store images next to a post (Hugo page bundle), but they do not display correctly in Sveltia CMS. For example, I can't select another image from the same collection for the cover image.

I think the problem is probably in the `media_folder` path, because Sveltia CMS doesn't see the images partially. I tried using `{{slug}}` but it doesn't work. I can see the cover image in the post preview, so I think `public_folder` is fine. The problem is that I can't change the image because "select image" doesn't include anything from the current collection, only from the general media folder, not the specific collection.

Please help me set this up correctly.
