### DISCUSSION TITLE
Is it possible to have the top-level json/yaml item a list?

### DISCUSSION THREAD

**Discussion by kriek** [sveltia/sveltia-cms#235] [Q&A] [answered]
Hi,

really nice project there, I like it already :)

Is it possible to manage the content of a yaml/json file when the top-level item is not an object but a list? For example, a yaml with the following content:
```
- date: '2024-10-25'
  event: dinner
- date: '2024-10-26'
  event: party
```

If this is supported, I was not able to find how such a collection is supposed to be described. It seems the top-level element must be an object or I am missing a collection configuration subtlety.
I'd like to know if this is supported or not. If it is not, that could be an improvement idea. It looks kind of an arbitrary restriction to me given that lists are otherwise well supported when further nested.

What works is to nest the items to make the top-level element an object and describe it in the collection:

```
entries:
  - date: '2024-10-25'
    event: dinner
  - date: '2024-10-26'
    event: party
```

```
collections:
  - name: entries
    label: Entries
    files:
      - label: Planning
        name: planning
        file: planning.yaml
        fields:
          - label: Entries
            name: entries
            widget: list
            fields:
              - label: Date
                name: date
                widget: string
              - label: Event
                name: event
                widget: string
```
