### DISCUSSION TITLE
Hide collection from Content UI

### DISCUSSION THREAD

**Discussion by jbelien** [sveltia/sveltia-cms#262] [Q&A] [answered]
Hello,

I'm using a collection to have a specific document library.
Here is my `config.yml` file:
```yaml
media_folder: static/files  # Where uploaded files are stored in the repository
public_folder: /files  # The public URL path for accessing the files

collections:
  ... // This is not really in my file, just to let you know that I have other collections 😁
  - name: documents
    label: Documents
    hidden: true
    folder: content/documents
    media_folder: /static/files/documents
    public_folder: /files/documents
    files: []
```

It works fine for the assets part:
![image](https://github.com/user-attachments/assets/13534e7b-31d0-4e75-b706-7245c5c01c5a)

But I would like to hide the "Documents" collection from the content part (because I don't plan to load any content there, it's only files):
![image](https://github.com/user-attachments/assets/505bd7e9-04ad-4b53-8dd9-59295872f942)

Is there a way to hide it ?
Or am I using a "workaround" and there is a cleaner way to do what I what to achieve ?

Thanks!
