### DISCUSSION TITLE
it seems that the list widget cannot loop after nested keys

### DISCUSSION THREAD

**Discussion by acivitillo** [sveltia/sveltia-cms#279] [Q&A] [answered]
I wanted to understand if this is intended behavior for a list widget, I am not able to find it in the documentation.

This works:

```yaml
  - label: "Foundations Keys"
    name: "keys"
    widget: "list"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "string" }
```

```yaml
keys:
  - content: with solid CI/CD and documentation
    title: Automation
  - content: Intuitive tools, clear APIs, and robust frameworks
    title: Developer Experience
  - content: Growing usage without exponentially growing tech debt and costs
    title: Scalability
  - content: Data governance, networking, and access
    title: Governance & Security
  - content: Clean, consistent, and enriched data for analysis
    title: Data Readiness
```

While this doesn't work:

```yaml
  - label: "Foundations Keys"
    name: "foundations.keys" #<- this doesn't seem to work
    widget: "list"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "string" }
```

```yaml
foundations:
  keys:
    - content: with solid CI/CD and documentation
      title: Automation
    - content: Intuitive tools, clear APIs, and robust frameworks
      title: Developer Experience
    - content: Growing usage without exponentially growing tech debt and costs
      title: Scalability
    - content: Data governance, networking, and access
      title: Governance & Security
    - content: Clean, consistent, and enriched data for analysis
      title: Data Readiness
```

**Comment by kyoshino** [comment, marked as answer]
Yeah, the `name` cannot contain dots because Sveltia CMS internally keeps an entry draft as a [flattened object](https://www.npmjs.com/package/flat) that uses dot notation for nested objects. I’ll mention the limitation when I create docs for Sveltia 😅 

So, this should work:

```yaml
- label: "Foundations"
  name: "foundations"
  widget: "object"
  fields:
    - label: "Keys"
      label_singular: "Key"
      name: "keys"
      widget: "list"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Content", name: "content", widget: "string" }
```
