### DISCUSSION TITLE
i18n and the folder structure

### DISCUSSION THREAD

**Discussion by fatyogi** [sveltia/sveltia-cms#294] [Q&A] [answered]
I am new to Sveltia and really enjoying the project, however I am a little puzzled with the folder structure for multilingual content management. According to Decap documentation, this is how you define your multilingual content structure in `config.yml` if you prefer to use the `multiple_folders` option:

```
i18n:
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  structure: multiple_folders
  locales: [en, de]
  default_locale: en
```

which then means if you let's say create a new post under the collections of posts with the `folder: content/posts`, the pages are going to be created as:
```
content/posts/en/XXXX-XX-XX-slug.yml
content/posts/de/XXXX-XX-XX-slug.yml
```

However, Hugo's multilingual support using multiple folders defines the folder structure differently. All the local language content resides in a language-specific content folder. As per Hugo's i18n documentation:

```
defaultContentLanguage = 'en'
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
  [languages.de]
    contentDir = 'content/de'
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 2
```

which means the folders will have the following structure:

```
content/en/posts/XXXX-XX-XX-slug.yml
content/de/posts/XXXX-XX-XX-slug.yml
```

How am I supposed to reconfigure Sveltia CMS or reconfighure Hugo i18n instead to marry the two structures?

Thanks,
Olaf

**Comment by kyoshino** [comment]
I don’t have a Hugo instance that I can test right away, but my quick test finds the `path` [folder collection](https://decapcms.org/docs/collection-folder/) option is what you need. Try this 🙂 

```yaml
collections:
  - name: posts
    label: Blog Posts
    i18n: true
    folder: content
    path: 'posts/{{slug}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    format: yaml
```

That’s `content/{{locale}}/posts/{{year}}-{{month}}-{{day}}-{{slug}}.yml`

**Reply by yurinaumov-com** [reply]
> I don’t have a Hugo instance that I can test right away, but my quick test finds the `path` [folder collection](https://decapcms.org/docs/collection-folder/) option is what you need. Try this 🙂
> 
> ```yaml
> collections:
>   - name: posts
>     label: Blog Posts
>     i18n: true
>     folder: content
>     path: 'posts/{{slug}}'
>     slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
>     format: yaml
> ```
> 
> That’s `content/{{locale}}/posts/{{year}}-{{month}}-{{day}}-{{slug}}.yml`

Thank you @kyoshino , ```path``` is definitely the way to specify the file name, however if I still use i18n multiple folders option - it will create two files: 
```
content/{{locale}}/posts/en/{{year}}-{{month}}-{{day}}-{{slug}}.yml
content/{{locale}}/posts/de/{{year}}-{{month}}-{{day}}-{{slug}}.yml
```
... which is not how it should be.

Besides, the {{locale}} is not translated to "en" or "de" in this case. It is just written to GitHub as-is.

Do you think it's a bug?

**Reply by kyoshino** [reply]
Hmm, interesting. With your `i18n` global config and my collection config, I got these two files:

- `content/de/posts/2025-01-05-hello.yml`
- `content/en/posts/2025-01-05-hello.yml`

Where did you put `{{locale}}`?

**Reply by kyoshino** [reply]
BTW, you can/should [test locally](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#working-with-a-local-git-repository) first when you make changes to the config file 🙂

**Comment by fatyogi** [comment]
Which option did you choose for i18n global support - is it
multiple_folders?

I put it the locale after content:

content/{{locale}}/….

But I also have the multiple folder option enabled.

Can you please send your whole config?

// Laconic style, sent from my phone

**Reply by kyoshino** [reply]
I used your config as is:

```yaml
i18n:
  structure: multiple_folders
  locales: [en, de]
  default_locale: en
```

You don’t need to add `{{locale}}` to the `folder` option. It’s just `content`.

**Reply by kyoshino** [reply]
So the whole but minimum config would look like:

```yaml
backend:
  name: github
  repo: owner/repo
  branch: main

media_folder: static/images
public_folder: /images

i18n:
  structure: multiple_folders
  locales: [en, de]
  default_locale: en

collections:
  - name: posts
    label: Blog Posts
    i18n: true
    folder: content
    path: 'posts/{{slug}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    format: yaml
    create: true
    delete: true
    fields:
      - name: title
        label: Post Title
        widget: string
        i18n: true
```

**Comment by fatyogi** [comment]
Ok, and what folder structure does it create?

en/post/….
de/post/…

(This is what Hugo expects for folders)

Or

post/en/…
post/de/…


// Laconic style, sent from my phone

**Reply by kyoshino** [reply]
As already said:

- `content/de/posts/2025-01-05-hello.yml`
- `content/en/posts/2025-01-05-hello.yml`

**Comment by fatyogi** [comment]
Interesting! So I should have just omitted the “content”… Does it mean that
the CMS considers all collection files reside under content/ by default and
not the root folder of the project?

Ok, thank you for the clarification - let me get back to my machine and try
again.

// Laconic style, sent from my phone

**Reply by kyoshino** [reply]
No, you still need `folder: content` for the collection.

**Comment by fatyogi** [comment]
Yep, this approach works! Does it apply to individual files too? For example, I have an individual file `content/about/_index.md` which I want to expose through CMS. And I am attempting to define a page resource like this:
```
      ###################### Pages / Indices ###################
      - name: "pages"
        label: "Pages"
        files:
          - label: "The Artist"
            name: "about"
            folder: content
            i18n: true
            path: 'about/'
            file: "_index.md"
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: "Is this page still a draft?", name: "draft", widget: "boolean", default: false }
                - { label: "Description", name: "description", widget: "text" }
                - { label: "Content", name: "body", widget: "markdown" }         
```

and the CMS doesn't see the file. Am I missing something? Thanks

**Reply by kyoshino** [reply, marked as answer]
For a [file collection](https://decapcms.org/docs/collection-file/), you need to specify a full path with the `file` option. And in Sveltia CMS, you can use `{{locale}}` in the path as described in the [README](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#better-i18n-support):

```yaml
  - name: pages
    label: Pages
    i18n: true
    files:
      - label: The Artist
        name: about
        file: 'content/{{locale}}/about/_index.md'
        i18n: true
        fields:
```
