### DISCUSSION TITLE
Needs a basic working example

### DISCUSSION THREAD

**Discussion by danurbanowicz** [sveltia/sveltia-cms#3] [General]
Firstly, thank you @kyoshino for all your work on this. A couple of questions:-

Is there a basic working example so that we can see which config is supported? I haven't been able to get Sveltia CMS to work at all so far (locally or on Netlify via GitHub backend) and I suspect it's due to some unsupported config that I've ported over from Netlify CMS.

Is there likely to be support for Git Gateway in the future? Requiring editors to have full read/write repo permissions is not going to be practical in a lot of cases.

**Comment by kyoshino** [comment]
@danurbanowicz Thanks for checking out Sveltia CMS! I’ve tested it with only a few of my clients using Netlify CMS, so I do expect various compatibility issues. Would you mind attaching your config file here (w/ any sensitive info redacted)? If not, I need to ask you to open the browser’s DevTools to check any errors logged there.

I’ll figure out how Git Gateway works! Maybe I can add support for it without extensive effort.

**Reply by danurbanowicz** [reply]
Thanks! Here's my `config.yml` below, and my test repo is [here](https://github.com/danurbanowicz/eleventy-sveltia-cms-starter) (using 11ty) if you want to clone.

```
backend:
  name: github
  repo: danurbanowicz/eleventy-sveltia-cms-starter
  branch: master

media_folder: "static/img"

collections:
  - name: "blog"
    label: "Post"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation"
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
```
In local repo mode, the CMS will open but all collection items have empty fields, and creating a new item results in an empty .md file.

In production on Netlify, I couldn't get the GitHub backend to work after following the steps; it would log me in but the Netlify "Authorized" window won't disappear, and the CMS won't load at all.
