### DISCUSSION TITLE
Issue with Astro and Sveltia CMS: Relation Fields Not Resolving Correctly for Multi-language Setup

### DISCUSSION THREAD

**Discussion by yacosta738** [sveltia/sveltia-cms#302] [Q&A] [answered]
Hi @kyoshino,
I’m having an issue with Astro and Sveltia CMS. I’m migrating from the old Netlify CMS to Sveltia CMS because it offers improvements over DecapCMS for managing multi-language content.

The Problem:
My website is multilingual, and collections are correctly stored in language-specific folders (e.g., `en` for English content and `es` for Spanish content). However, when I try to relate collections in Sveltia CMS, it links them incorrectly.

For example, the author relation is saved as `author: yuniel-acosta`, but Astro expects the relation to be `en/yuniel-acosta` for English content or `es/yuniel-acosta` for Spanish content.

What I Tried:
I attempted using value_field: `'{{locale}}/{{slug}}'`, but this results in `author: /yuniel-acosta` instead of the expected `en/yuniel-acosta` or `es/yuniel-acosta`.

CMS Configuration (config.yml):

```yaml
local_backend: true

logo_url: /logo.svg

backend:
  name: 'github'
  repo: yacosta738/yacosta738.github.io
  branch: main
  base_url: https://yunielacosta.com
  automatic_deployments: false
  accept_roles:
    - admin
    - editor

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

publish_mode: editorial_workflow

media_folder: 'public/images'
public_folder: '/images'

i18n:
  structure: 'multiple_folders'
  locales: ['en', 'es']
  default_locale: 'en'
  canonical_slug:
    key: defaultLocaleVersion
    value: 'en/{{slug}}'
```

Astro Configuration (config.ts):

```typescript
import { glob } from 'astro/loaders';
import { defineCollection, reference, z } from 'astro:content';

const blogCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.date(),
    cover: z.string(),
    author: reference('authors'),
    tags: z.array(reference('tags')),
    categories: z.array(reference('categories')),
    isExternalLink: z.boolean().default(false),
    link: z.string().optional(),
    draft: z.boolean(),
  }),
});

const authors = defineCollection({
  loader: glob({ pattern: '**/[^_]*.json', base: './authors' }),
  schema: z.object({
    name: z.string(),
    image: z.string(),
    rol: z.string(),
    bio: z.string(),
    email: z.string(),
    social: z.array(
      z.object({
        name: z.string(),
        url: z.string(),
        icon: z.string(),
      })
    ),
  }),
});

export const collections = {
  blog: blogCollection,
  authors,
};
```

[Example Branch](https://github.com/yacosta738/yacosta738.github.io/tree/refactor/migration-netlify-cms-to-slveltia-cms-issue)

Any ideas on how to fix the relation field so that it correctly includes the locale (en/ or es/)? I appreciate any help!
