### DISCUSSION TITLE
How to enable omit_empty_optional_fields?

### DISCUSSION THREAD

**Discussion by bbjay** [sveltia/sveltia-cms#310] [Q&A]
I'm trying to get `omit_empty_optional_fields: true` working, but im unsure where to put it or if there's some limitation.
What I have tried so far is putting this:
```yml
output:
  omit_empty_optional_fields: true
```
basically on every level from config root to fields.

I have the following in my collections:
```yml
  collections:
    - name: "about"
      label: "About"
      i18n: true
      files:
        - label: "About Page"
          name: "content"
          file: "content/{{locale}}/about.md"
          i18n: true
          fields:
            - {label: Title, name: title, widget: string, i18n: true}
            - {label: Slug, name: slug, widget: string, i18n: true, required: false}
            - {label: Test, name: test, widget: string, required: false}
            - label: Main
              name: main
              required: false
              i18n: true
              widget: "object"
              fields:
                - { label: "Display Name", name: "name", widget: "string", i18n: true, required: false }
            - {label: Body, name: body, widget: markdown, i18n: true}
```

What I get as output in about.md is
```yml
---
title: About
slug: about
test: ''
main: null
---
Hello
```

But I expect it to be
```yml
---
title: About
slug: about
---
Hello
```
with the empty `required: false` fields omitted.
The `main` field is not there when left empty on first save, but adding and removing it again leaves it with `main: null`.

 Am I missing something?
