### DISCUSSION TITLE
slug management

### DISCUSSION THREAD

**Discussion by sardarms** [sveltia/sveltia-cms#96] [Q&A] [answered]
I am trying to control the output of the slug (instead of the title) by following this option:

`... # whatever collection
- slug: '{{field.slug}}'
- fields:
  - name: title
     label: Title
     widget: string
  - name: slug
     label: Slug
     widget: slug
     slug: 'custom-slug-{{title}}'`

I got it from [here](https://github.com/decaporg/decap-cms/issues/445#issuecomment-621700949) - Decap CMS issue [445](https://github.com/decaporg/decap-cms/issues/445). 

But seems like the slug is just some numbers like [this](https://github.com/decaporg/decap-cms/issues/445)

Is there any way to control the slug of the post? 

Thanks in advance.

**Comment by kyoshino** [comment]
The example doesn’t work in Sveltia CMS because it relies on a [custom widget](https://decapcms.org/docs/custom-widgets/), which is not yet supported in Sveltia.

You can instead use the standard [string widget](https://decapcms.org/docs/widgets/#string) to enter a slug manually:

```yaml
collections:
  - name: posts
    label: Posts
    slug: '{{field.slug}}'
    fields:
      - name: title
        label: Title
        widget: string
      - name: slug
        label: Slug
        widget: string # instead of slug
```

Or, simply use a [random ID](https://github.com/sveltia/sveltia-cms#use-a-random-id-for-an-entry-slug) as a slug:

```yaml
collections:
  - name: posts
    label: Posts
    slug: '{{uuid_short}}'
```
