### ISSUE TITLE
`allow_multiple`-option of the image-widget not working

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#10]
```
- { name: "img", label: "Image", widget: image, allow_multiple: true }
```
The `allow_multiple`-option of the image-widget seems to not be supported.
Or just the media-library does not support multiple-selection, which would make the option in line with the [decap-cms-Doc](https://decapcms.org/docs/widgets/#image)
> allow_multiple: (default: true) when set to false, multiple selection will be disabled even if the media library extension supports it

**Comment by kyoshino** [comment]
The `allow_multiple` is only for external media libraries like [Cloudinary](https://decapcms.org/docs/cloudinary/) and [Uploadcare](https://decapcms.org/docs/uploadcare/), which are not supported yet. Well, I know there is an [issue with Netlify/Decap CMS](https://github.com/decaporg/decap-cms/issues/6730) for supporting the option with the default media library. I’ll take care of it after adding support for external libraries and understanding the behaviour.

**Comment by kyoshino** [comment]
Does it actually work in Decap? https://github.com/decaporg/decap-cms/issues/6730 is closed as duplicate but is not fixed yet, I think.

**Comment by ekin04** [comment]
sorry my bad, i have try fast with  decap 

`backend:
  name: test-repo`

  and here the ui work good, but when use other backend we have the same problem

**Comment by kyoshino** [comment]
Ah the Test backend. I see.

I’ll work on this anyway, but multiple image selection is not recommended because generally each image should have an alt text for accessibility and SEO. You can instead use the List widget:

```yaml
      - name: thumbnails
        label: Featured Images
        widget: list
        fields:
          - name: src
            label: Source
            widget: image
          - name: alt
            label: Alt Text
            widget: string
```
