### ISSUE TITLE
Configuration property `summary` doesn't show value `false`

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#104]
If I use the 'summary' property within my 'collections' configuration. `false` value is not displayed correctly, even if i apply tenary('Yes', 'No').

```yml
collections:
  # Data `Authors`
  - name: data-authors
    label: "Data/Authors"
    label_singular: "Data/Author"
    folder: "data/authors"
    create: true
    format: yml
    extension: yaml
    i18n: false
    editor:
      preview: false
    summary: "{{name}} | Default: {{isdefault|ternary('Yes', 'No')}}"
    fields:
      - label: Name
        name: name
        widget: string
      - label: Display Name
        name: displayName
        widget: string
      - label: Is Default Author
        name: isdefault
        widget: boolean
        default: false
```

![image](https://github.com/sveltia/sveltia-cms/assets/3283596/c58257bd-0b00-445c-80f9-ad0efe50a9ba)
