### ISSUE TITLE
Configuration property `summary` doesn't show the correct value for `{{slug}}`

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#105]
I use Sveltia together with Hugo. I would like to manage my tags cleanly and structure them accordingly. I would like to display the configured slug for the respective tag using the `summary` function.

However, the value from the `slug` field is not used here, but a new one is generated.

```yml
# Collection `Tags`
  - name: pages-tags
    label: "Pages/Tags"
    label_singular: Tag
    folder: "content/tags"
    path: "{{slug}}/index"
    icon: local_offer
    i18n:
      structure: multiple_files
      locales:
        - en
        - de
    create: true
    summary: "{{title}} | {{slug}}"
    fields:
      - label: Slug
        name: slug
        widget: string
        i18n: duplicate
      - label: Translation Key
        name: translationKey
        widget: string
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Draft
        name: draft
        widget: boolean
        default: true
        i18n: duplicate
```

Wrong used `slug`
![image](https://github.com/sveltia/sveltia-cms/assets/3283596/04e10beb-53f6-4fe5-8aff-dd8351b502a2)

Configured values for Tag `.NET`
![image](https://github.com/sveltia/sveltia-cms/assets/3283596/2b29367a-96fe-4b5c-b393-48879000034d)

Configured values for Tag `C#`
![image](https://github.com/sveltia/sveltia-cms/assets/3283596/382c941b-0bd1-4729-ad40-4f2383823c8b)
