### ISSUE TITLE
Feature Request: Widget `compute`

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#111]
This widget is a read-only element that updates itself based on events (focus change, etc.). It should take over existing content and transform it if necessary.

The configuration for this could look as follows.
```yml
fields:
  - label: Slug
    name: slug
    widget: string
    i18n: duplicate
  - label: TranslationKey
    name: translationKey
    widget: compute
    value: posts-{{fields.slug}}
```
