### ISSUE TITLE
Feature Request: Allow Markdown Syntax for `before_input` and `after_input`

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#113]
For better formatting of the fields, using Markdown syntax for the field properties `before_value` and `after_value` would be advantageous. This would enable providing additional information with a link or emphasizing keywords.

```yml
- label: Draft State
  name: draft
  widget: boolean
  default: true
  i18n: duplicate
  after_input: If enabled, the page is not ***published***.
  preview: false
```
