### ISSUE TITLE
Unable to preview image in editor

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#116]
In my migration to Sveltia CMS, I have encountered the issue that not all of my hero images for my blog posts are displayed correctly in the editor as well as in the collection listing.

![image](https://github.com/sveltia/sveltia-cms/assets/3283596/079e09bc-89ef-48d9-9aed-05cf4bf99b6d)

The first three blog articles are sourced from a centrally available folder that contains various subfolders. (`media_folder` = `assets/` & `public_folder` = `/`). On the other hand, the fourth blog article uses an image from its own article directory.

Editorview with not working Image preview:
![image](https://github.com/sveltia/sveltia-cms/assets/3283596/271ffb08-92f0-4d12-84bd-28d46c3329b3)

Editorview with working Image preview:
![image](https://github.com/sveltia/sveltia-cms/assets/3283596/f145674b-47fd-4bb9-89a6-ddd5e969ef6f)

Configuration:
```yml
- label: Hero Image
  name: hero
  widget: image
  i18n: true
  preview: false
- label: Hero Anchor
  name: heroAnchor
  widget: select
  i18n: true
  preview: false
  options: ["TopLeft", "TopCenter", "TopRight", "Left", "Center", "Right", "BottomLeft", "BottomCenter", "BottomRight", "Smart"]
  default: ["Smart"]
```

**Comment by kyoshino** [comment]
How the `media_folder` and `public_folder` for the posts collection look like? As the [Decap doc](https://decapcms.org/docs/collection-folder/#media-and-public-folder) says, you need these properties for the collection:

```yaml
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
```

I’m testing now — one entry contains an image from the global asset folder, and another contains an image from an entry-relative path, and both displays fine:

<img width="276" alt="image" src="https://github.com/sveltia/sveltia-cms/assets/2929505/b366eff6-3d79-4dd7-81c0-7fd3bd10651f">

<br>

<img width="479" alt="image" src="https://github.com/sveltia/sveltia-cms/assets/2929505/d97aedc1-0539-4ee5-976a-37ac1426c2fd">

<br>

<img width="480" alt="image" src="https://github.com/sveltia/sveltia-cms/assets/2929505/dee07233-6280-44c6-a7c7-81cfb17bfffe">

But I’ve realized that, currently when I select a new image from the image selector, the preview becomes empty. (Once saved, it will be displayed.) It’s a different bug; I’ll fix it.

<img width="488" alt="image" src="https://github.com/sveltia/sveltia-cms/assets/2929505/ed5a1eb6-959b-45ae-af5e-901efbaa3ce2">
