### ISSUE TITLE
Widget `select` not loaded correctly

### ISSUE THREAD

**Issue by samtrion** [sveltia/sveltia-cms#118]
Based on the following configuration, when I create a new Site or open a Page with explicit set value for `heroAnchor` is everything fine.

```yml
- label: Hero Anchor
  name: heroAnchor
  widget: select
  i18n: true
  preview: false
  options: ["TopLeft", "TopCenter", "TopRight", "Left", "Center", "Right", "BottomLeft", "BottomCenter", "BottomRight", "Smart"]
  default: "Smart"
```

However, when I open a page where `heroAnchor` has not been used previously, the `default` value is not applied correctly. For the sake of data consistency, an update to the stored data should be offered in this case.
