### ISSUE TITLE
One of the latest updates seems to break local development

### ISSUE THREAD

**Issue by Because789** [sveltia/sveltia-cms#124]
I have a project where local development worked with a previous version of Sveltia, but now it doesn't. Here is my config:

```yml
# backend: not relevant now, since only local dev

media_folder: "src/assets/images"
public_folder: "@assets/images"

i18n:
    structure: "multiple_folders"
    locales:
        - "de"
        - "en"
    default_locale: "de"
    save_all_locales: false

collections:
    - name: "posts"
      i18n: true
      label: "Blog Posts"
      folder: "src/content/blog"
      media_folder: "/src/assets/images/blog"
      public_folder: "@assets/images/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Description"
            name: "description"
            widget: "string"
            i18n: true
          - label: "Publish Date"
            name: "pubDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Image"
            name: "heroImage"
            widget: "image"
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
```

When I open my Astro project on http://localhost:4321/admin/index.html and select `src/content/blog`, no posts show up (they previously did). When I save a new asset, it's saved at: `src/content/blog/src/assets/images/whatever.jpg`. A new post is saved at `src/content/blog/src/content/blog/de/test.md` and `src/content/blog/src/content/blog/en/test.md`
