### ISSUE TITLE
field with attribute widget list blocks content creation

### ISSUE THREAD

**Issue by loicginoux** [sveltia/sveltia-cms#126]
Given this config:
```yaml
collections:
    - name: "posts"
      i18n: true
      label: "Blog Posts"
      folder: "src/content/blog"
      create: true
      delete: true
      fields:
          - label: "Tags"
            name: "tags"
            widget: "list"
```
I should be able to create a new post with a tag list, but I have an error when saving the new post that blocks me from creating content.

<img width="1206" alt="Screenshot 2024-03-25 at 23 17 36" src="https://github.com/sveltia/sveltia-cms/assets/824936/06c8a348-3883-4e34-9bd2-b39fff5e90f9">

It does not happen when duplicating an existing post, and it is definitely an issue with this field because it works when I have other type of fields (string, boolean, text, object, etc..)
