### ISSUE TITLE
JavaScript error on save

### ISSUE THREAD

**Issue by jonnyowenpowell** [sveltia/sveltia-cms#134]
Hey!

Since v0.21.2 I see the following message in the console when saving a collection, and the page becomes unresponsive.

```
sveltia-cms.js:627 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_default')
    at t.$$.update (sveltia-cms.js:627:238808)
    at PT (sveltia-cms.js:1:5502)
    at Ze (sveltia-cms.js:1:5217)
```

My config is:

```
backend:
  name: github
  repo: jonnyowenpowell/<repo name>
  branch: main
site_url: http://localhost:1313
logo_url: /img/logo.png
media_folder: static/img
public_folder: /img
search: true
collections:
  - name: blog
    label: Blog
    folder: 'content/blog'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```
