### ISSUE TITLE
Write local timezone in dates when picker_utc = false

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#143]
In `datetime` widget, when I set `picker_utc` to `false`, the cms UI shows time in my local time zone (GMT-3:00). But when I save the item, the time is written as UTC in the file (for example, `2019-06-25T00:00:00.000Z`). This is confusing and counter-intuitive, I think.

I think it would be better that data written was equivalent to that shown in the UI, so:

- `picker_utc: true`: time written in UTC
- `picker_utc: false`: time written in local time zone

**Comment by kyoshino** [comment]
Will check!

**Comment by kyoshino** [comment]
I can’t reproduce the issue with this simple configuration:

```yaml
      - label: 'Publish Date Local'
        name: 'pubDateLocal'
        widget: 'datetime'
        picker_utc: false
      - label: 'Publish Date UTC'
        name: 'pubDateUTC'
        widget: 'datetime'
        picker_utc: true
```

which will be saved as

```yaml
  pubDateLocal: 2024-05-14T19:27
  pubDateUTC: 2024-05-15T03:27:00.000Z
```

Can you paste your field configuration here?
