### ISSUE TITLE
Multiple Files JSON File Structure - Localized File Collections

### ISSUE THREAD

**Issue by CarloBu** [sveltia/sveltia-cms#146]
Hello, it's me again, I'm trying add multiple-folders JSON structure to the Sveltia CMS so that the client can easily navigate and change localized navigation links:
![image](https://github.com/sveltia/sveltia-cms/assets/145860771/2a25777d-397e-415c-8180-816c4adc8ad6)

Sveltia CMS let me directly define files:
```
  - label: Navigation
    name: navigation
    create: false
    delete: false
    icon: link
    i18n: true
    format: json
    extension: json
    files:
      - file: 'src/locales/lt/headerData.json'
        label: 'header'
        name: 'headerData'
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            i18n: duplicate
            fields:
              - label: "Text"
              ...
      - file: 'src/locales/lt/footerData.json'
        label: 'footer'
        name: 'footerData'
        fields:   
          - label: "Links"
          ...
      - file: 'src/locales/lt/shared.json'
        label: 'shared'
        name: 'sharedData'
        fields:   
          - label: "Title"
          ...
```
This setup works well, and surprisingly, Sveltia CMS functions with a single JSON file for both locales. However, the localization library I use is highly opinionated and uses a multiple-folder JSON file structure. It also doesn't support nested folders, which leads to issues. This is the folder structure of localized json files that I setup.
![image](https://github.com/sveltia/sveltia-cms/assets/145860771/5a07e218-b3ec-4c83-a1d5-3a79d00a615d)

Would it be possible for you to add Multiple Folders JSON File Structure?

In this case, I would imagine the workflow:
provide the file path of json file:
    i18n: true
    files:
      - file: 'src/locales/lt/headerData.json'
With i18n flag present, the Sveltia would look for locale identifiers in the JSON. If it does not find any, it would look for the second locale folder: 'src/locales/en/headerData.json'. Or just use some flag field to trigger the multiple-folder locale json structure,

I hope I explained my idea clearly.

**Comment by kyoshino** [comment]
It’s an open issue in Netlify/Decap CMS and on my todo list 😎

- https://github.com/decaporg/decap-cms/issues/5280

I was wondering how to solve this without breaking backward compatibility, but it’s probably not hard to do it.

1. Allow developers to use the `{{locale}}` template tag in the file path `file` path, e.g. `src/locales/{{locale}}/shared.json`
2. Sveltia CMS enables multiple files/folders mode only if `{{locale}}` is used and the `multiple_files` or `multiple_folders` i18n structure is configured.
3. Sveltia CMS generates files for all the locales while replacing `{{locale}}`

Let’s see if this works.

**Comment by CarloBu** [comment]
Yes, I was thinking about a solution too that does not break the existing workflow, and your src/locales/{{locale}}/shared.json idea looks like an elegant solution. {{locale}} does not break any existing logic. 👍

**Comment by CarloBu** [comment]
thank you for the workaround, will try.

**Comment by kyoshino** [comment]
Done in [v0.29.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.29.0) 🚢

**Comment by CarloBu** [comment]
whoah! Thanks a lot! It was the last barrier to building a functional fully i18n web personal stack. 💯

**Comment by CarloBu** [comment]
@kyoshino, 
serious question:
how are you so productive with this project? Decap CMS has 500 contributors, but their last commit was one month ago with a single feature.

**Comment by kyoshino** [comment]
I just want to ship a much better product than Decap CMS 😄 The i18n support is my particular concern since my own clients usually require a multilingual setup. A new client wants to have content in Japanese, English and French.

Not sure what’s happening with Decap. There are even no maintainer responses to new issues and PRs these days. Perhaps some of them have been laid off, or the company has limited their time working on the project 🤔

**Comment by CarloBu** [comment]
Yeah, something strange is happening. There are over 500 open issues, and most of them with bug tags concern me. I think I have tried almost all the CMSs on the market, from closed-source Contentful to open-source Fresh Star Payload CMS. Most of them were overkill for my needs, so I narrowed my search to Git-based CMSs to avoid running a server for the CMS or being at the mercy of corporations that might pull the plug. In my humble opinion, the Keystatic CMS is great, I liked the keystatic.cloud, but I didn't like the UX; it is too dev-centric with all the Git functions. Pages CMS is great too; I liked the UI a lot, but the i18n is non-existent and it lacks some advance features.

After some testing, I thought I would stick with the half-decent Decap until I found your CMS. This is all I need, and the i18n is perfect. In Europe, i18n is a must. I'm glad I found your CMS. 👍

**Comment by CarloBu** [comment]
I think I encountered a bug when I try to upload an image with a localized file structure. It doesn't matter whether it is an md, yaml, or json file. The image won't upload when there is a localized file structure. Additionally, I can't see my local images in the "All Asset" window.

To recreate, run this schema:

```
collections:
  - label: 'Test'
    name: 'test'
    create: true
    format: json
    extension: json
    i18n: duplicate
    editor:
      preview: false
    files:
      - file: 'src/content/{{locale}}/test.json'
        label: Test Data
        name: testData
        slug: testData
        i18n: duplicate
        editor:
          preview: false
        fields:
          - label: Test Image
            name: testImage
            widget: object
            i18n: duplicate
            fields:
              - {label: Image, name: src, widget: image, i18n: duplicate}
```


https://github.com/sveltia/sveltia-cms/assets/145860771/3f500ef6-c91b-4d79-9f11-fa550e40d2ab
