### ISSUE TITLE
Dividers jump to another position when I change current collection

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#147]
Dividers in collections list jump from their original position when I change between collections. To reproduce:

1. log in > dividers are ok
2. change to another collection > dividers jump
3. change again to another collection > no more jumps, but divider keeps wrong position
4. open any item/file, make any edits, then return to collection list > divider keeps wrong position
5. log out and in again > dividers are ok again

I tested with a collection list like this:

- folder collection
- folder collection
- folder collection
- folder collection
- **divider**
- folder collection (this collection changes position with the divider below
- **divider** (this divider changes position with the collection above)
- file collection
- file collection

This happens locally and also on web.

I know you've just landed [dividers for collections list](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#adding-dividers-to-the-collection-list), and they are awesome! So do they that I was eager to test them... Anyway, thank you for this feature!

**Comment by kyoshino** [comment]
Will check! 🤔

**Comment by kyoshino** [comment]
Testing with my local client instances but can’t reproduce the issue. @CarloBu Do you see the problem?

**Comment by CarloBu** [comment]
[kyoshino](https://github.com/kyoshino), It works perfectly for me. 
I will try to reproduce

**Comment by CarloBu** [comment]
[josineto](https://github.com/josineto), I can't reproduce the issue, 
Can you try to check a test collection schema to see if the divider is still jumping?

config.yaml
```
backend:
  name: github
  repo: your/repo
  branch: main
  base_url: http://localhost:4321
  auth_endpoint: /api/auth

media_folder: /src/assets/imgs
public_folder: /src/assets/imgs

collections:
  - label: Test1
    name: test1
    folder: src/content/test1
    create: true
    fields:
      - {label: Title, name: title, widget: string}

  - label: Test2
    name: test2
    folder: src/content/test2
    create: true
    fields:
      - {label: Title, name: title, widget: string}
    
  - label: Test3
    name: test3
    folder: src/content/test3
    create: true
    fields:
      - {label: Title, name: title, widget: string}

  - label: Test4
    name: test4
    folder: src/content/test4
    create: true
    fields:
      - {label: Title, name: title, widget: string}

  - divider: true
    name: d1

  - label: Test5
    name: test5
    folder: src/content/test5
    create: true
    fields:
      - {label: Title, name: title, widget: string}

  - divider: true
    name: d2

  - label: Test6
    name: test6
    folder: src/content/test6
    create: true
    fields:
      - {label: Title, name: title, widget: string}

  - label: Test7
    name: test7
    folder: src/content/test7
    create: true
    fields:
      - {label: Title, name: title, widget: string}
```

if the test schema divider is not jumping, then it means something is with your config.yaml
