### ISSUE TITLE
Suggestion: hidden list field with current item index

### ISSUE THREAD

**Issue by josineto** [sveltia/sveltia-cms#172]
The idea is: in a List widget with fields (e.g. not "simple string list"), one could add a hidden field that holds the index of the current item in that list, like:

```yaml
list:
- fruit: apple
  index: 0 # <---
- fruit: banana
  index: 1 # <---
```

It could be a `hidden` widget with `default: '{{index}}'`, or a `compute` widget with `value: '{{index}}'`, or even something else...
