### ISSUE TITLE
Relation field does not seem to work when inside a Variable Type Widgets

### ISSUE THREAD

**Issue by AntoineBx** [sveltia/sveltia-cms#192]
Hello, my "relation primary" field doesn't work when inside variable type widgets, it works otherwise

```
fields:
      - label: 'Plain URL or relation to page'
        name: 'sections'
        widget: 'object'
        i18n: true
        types:
          - {label: URL, name: url, widget: string, i18n: true, required: false, pattern: ['/^[a-zA-Z0-9-]+$/', 'Only simple chars and "-" for separation are allowed'], hint: 'Override relation pages below'}
          - label: 'relation primary' 
            name: 'relation_primary'
            widget: 'relation'
            i18n: true
            collection: 'pages'
            required: false
            multiple: false
            search_fields: ['page_id']
            value_field: 'page_id'
            display_fields: ['page_id']
```

**Comment by kyoshino** [comment]
Looks like the problem is due to a misconfiguration. Under `types`, there has to be `fields` like [this example](https://decapcms.org/docs/widgets/#example-configuration), even if there is only a single field. It’s kinda redundant, but your config would look like this:

```yaml
    fields:
      - label: Plain URL or relation to page
        name: sections
        widget: object
        i18n: true
        types:
          - label: URL
            name: url
            widget: object
            fields:
              - label: URL
                name: url
                widget: string
                i18n: true
                required: false
                pattern:
                  ["/^[a-zA-Z0-9-]+$/", 'Only simple chars and "-" for separation are allowed']
                hint: Override relation pages below
          - label: Page ID
            name: page_id
            widget: object
            fields:
              - label: relation primary
                name: relation_primary
                widget: relation
                i18n: true
                collection: pages
                required: false
                multiple: false
                search_fields: [page_id]
                value_field: page_id
                display_fields: [page_id]
```

In the near future, I’ll implement a configuration validator to help find such issues. 😅
