### ISSUE TITLE
The image files with the same filename are overridden

### ISSUE THREAD

**Issue by CarloBu** [sveltia/sveltia-cms#194]
Hi @kyoshino 
I just found out that when the client uploads another project image with the same filename (for example, viz1.jpg), the existing file from a completely different project gets overwritten. 
Is it possible to prevent this by automatically renaming the new the same filename file, for example, from viz1.jpg to viz1-1.jpg, to viz1-2.jpg, to viz1-3.jpg e.t.c? Or I doing something wrong?

```
the yaml schema:
  - label: Projects
    name: projects
    folder: src/content/projects
    media_folder: /src/assets/projecsImages
    public_folder: /src/assets/projecsImages
    icon: domain_add
    create: true
    i18n: true
    format: yml
    extension: yaml
    thumbnail: pbImages.0.src
    slug: '{{title | localize}}'
    editor:
      preview: false
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - label: Project Images
        name: images
        widget: list
        i18n: duplicate
        fields:
            - {label: Image, name: src, widget: image, i18n: duplicate}
```
