### ISSUE TITLE
Relation radio buttons stopped working in v0.39.3

### ISSUE THREAD

**Issue by CarloBu** [sveltia/sveltia-cms#203]
Hey, Kyoshino, I Just found out that the latest build does not work with dropdown relation menu is not working.
in my case the projectStatus does give me warning that the field is required and it does not register the input.
I need to roll back to 0.39.2 to make it work again.
<script src="https://unpkg.com/@sveltia/cms@0.39.2/dist/sveltia-cms.js"></script>

.
![image](https://github.com/user-attachments/assets/5228f56a-54ad-4c4a-9259-c77336863354)

```
  - label: Projekto Būsena
    name: projectStatus
    folder: src/content/projectStatus
    create: true
    icon: dashboard_customize
    i18n: true
    format: yml
    extension: yaml
    slug: '{{status | localize}}'
    editor:
      preview: false
    fields:
      - label: Projekto Būsena
        name: status
        widget: string
        i18n: true
  
 
  - label: Projektai
    name: projects
    folder: src/content/projects
    media_folder: /src/assets/projectImages
    public_folder: /src/assets/projectImages
    icon: domain_add
    create: true
    i18n: true
    format: json
    extension: json
    thumbnail: images.0.src
    summary: "{{title}} - {{date | date('YYYY-MM-DD')}}"
    slug: '{{title | localize}}'
    editor:
      preview: false
    fields:
      - label: 'Ar tai Naujiena?'
        name: 'isNews'
        required: false
        widget: object
        i18n: duplicate
        fields:
          - label: 'Naujienos Aprašymas'
            name: 'newsDescription'
            widget: text
            i18n: true
            required: true
            hint: 'Trumpas naujienos aprašymas'
      - {label: Pavadinimas, name: title, widget: string, maxlength: 100, i18n: true}
      - {label: Aprašymas, name: description, widget: text, maxlength: 430, i18n: true, hint: 'Trumpas aprašymas'}
      - label: 'Klientas'
        name: 'client'
        required: false
        widget: object
        i18n: duplicate
        fields:
          - {label: 'Klientas', name: 'clientName', widget: string, i18n: true, required: true, hint: 'Kliento pavadinimas'}
      - label: 'Plotas'
        name: 'area'
        required: false
        widget: object
        i18n: duplicate
        fields:
          - {label: Plotas m2, name: propertyArea, widget: number, required: true, i18n: duplicate}
      - {label: Kategorija, name: category, widget: relation, collection: categories, i18n: duplicate, multiple: true, value_field: defaultLocaleVersion, display_fields: [category]}      
      - {label: Projekto Būsena, name: status, widget: relation, dropdown_threshold: 10, 
      collection: projectStatus, i18n: duplicate, value_field: defaultLocaleVersion, 
      display_fields: [status]}                <---- this one does not register the input
      - {label: Projekto Vieta, name: projectLocation, widget: string, i18n: true}
      - label: 'Įgyvendinimo Metai'
        name: 'realizationYear'
        required: false
        widget: object
        i18n: duplicate
        fields:
          - {label: Metai, name: year, widget: number, default: 2024, required: true, i18n: duplicate}

      - {label: Paskelbimo Data, name: date, widget: datetime, i18n: duplicate}
      - label: "Thumbnail Vaizdo Pozicija"
        name: "imagePosition"
        widget: "select"
        i18n: duplicate
        required: true
        options:
          - { label: "Kairėje", value: "left" }
          - { label: "Kairėje centre", value: "left-center" }
          - { label: "Centre", value: "center" }
          - { label: "Dešinėje centre", value: "center-right" }
          - { label: "Dešinėje", value: "right" }
        default: "center"
      - label: Projekto Nuotraukos
        name: images
        widget: list
        i18n: duplicate
        fields:
            - {label: Nuotrauka, name: src, widget: image, i18n: duplicate}
```
