### ISSUE TITLE
Cannot update file localization

### ISSUE THREAD

**Issue by trietng** [sveltia/sveltia-cms#205]
I was doing some localization on a md file and I think I encountered some weird behavior. Not sure if it was due to my incorrect config file or a bug, but I can only save the non-default localizations and not when I opened the file for updates.

![image](https://github.com/user-attachments/assets/1a32e22d-fc55-4304-a566-ab82fe5e093c)

![image](https://github.com/user-attachments/assets/f7b88df4-4816-4297-a9cb-7a1d6c37e64a)

This happened on the latest version (v0.39.10). Astro version is 4.8.2.

- Config file

```yaml
i18n:
  structure: multiple_folders
  locales: [en, vi]
  default_locale: en
collections:
  - label: Pages
    name: pages
    i18n: true
    files:
      - label: Home
        name: home
        file: src/pages/{{locale}}/index.md
        i18n: true
        format: markdown
        fields:
          - { label: Layout, name: layout, widget: hidden, default: ../../layouts/IndexLayout.astro, i18n: duplicate }
          - label: Title
            name: title
            widget: object
            i18n: duplicate
            fields:
              - { label: Greeting, name: greeting, widget: string, i18n: true }
              - { label: Name, name: name, widget: string, i18n: true }
          - { label: Summary, name: summary, widget: string, i18n: true }
 ```
