### ISSUE TITLE
_index.md in Hugo - it is still showing up and editable 

### ISSUE THREAD

**Issue by sardarms** [sveltia/sveltia-cms#210]
Not sure if this is a bug, but I can still see and edit the _index.md file in my hugo site. 

Here is my code
```
collections:
  
  - name: 'posts-en'
    label: 'Posts-En'
    folder: 'content/en/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', dateFormat: 'YYYY-MM-DD', format: 'YYYY-MM-DD', required: true }
      - { label: "Featured image", name: "feature_image", widget: "image", required: false }
      - { label: "Description for SEO", name: "description", widget: "string", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false, field: { name: text, label: Text, widget: string } }
      - { label: "Tags", name: "tags", widget: "list", required: false, field: { name: text, label: Text, widget: string } }
      - { label: "Author", name: "author", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
``` 

In the blog folder, I have _index.md file and some other post. But in the editor, I can still access this and edit the content of the _index.md file.
