### ISSUE TITLE
New content in collection not recognized

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#211]
I'm experiencing the same issue with {{slug}}/index.md as I was with _index.md.

Steps to reproduce:
```yml
name: hugo-content-default
description: The scms equivalent of `hugo new page-title/index.md`
label: Content
collection_type: folder
folder: content
path: "{{slug}}/index"
slug: "{{slug}}"
identifier_field: title
format: yaml-frontmatter
extension: md
fields:
  - import: field scms-collection-destination
    field_type: import
  - import: field hugo-content-title
    field_type: import
  - import: field hugo-content-date
    field_type: import
  - import: field hugo-content-draft
    field_type: import
  - import: field hugo-content-body
    field_type: import
create: true
delete: false
preview_path_date_field: ""
```

Create a post, it creates (but the date field crashes hugo for some reason, unrelated here). Commenting the date field rebuilds the site, but the new file isn't recognized by the collection.
