### ISSUE TITLE
noob: Hugolify Sveltia installation

### ISSUE THREAD

**Issue by richtong** [sveltia/sveltia-cms#226]
I can't wait to use Sveltia! But in trying to get it work, I am starting a fresh, so I don't have decap running. Your guide said to try the hugolify/sveltia-cms hugo module, so I did but I'm getting an "unexpected error". Is there a way that I can debug this to figure out what is going on. Here is my simplified hugo.yaml

```
baseURL: /
languageCode: en-us
title: My New Hugo Site
module:
  imports:
    - path: github.com/richtong/gohugo-theme-ananke
    - path: github.com/hugolify/hugolify-sveltia-cms
```

I do indeed get to the sveltia site with `localhost:1313/admin`

I'm using Chrome (and made the adjustments so Brave works), but when I browse to a repo, I get

![image](https://github.com/user-attachments/assets/e63abe1b-44d5-4536-a612-b06af2178061)

and then i get this error. Looking at the code here, I don't see an obvious problem it is basically replacing the decap js include with sveltia.

![image](https://github.com/user-attachments/assets/9d322c36-793d-4023-a89a-ea186d822402)
