### ISSUE TITLE
My summary filters don't seem to work

### ISSUE THREAD

**Issue by AntoineBx** [sveltia/sveltia-cms#255]
Hello kyoshino!
Whether it is ternary filter or | upper, it return nothing for me
maybe i'm missing something tho
```
fields:
              - label: general
                name: section
                widget: object
                i18n: duplicate
                collapsed: true
                required: true
                summary: " container: {{fields.containerize | ternary('yes','no')}} "
                fields:
                  - label: container?
                    name: containerize
                    widget: boolean
                    default: true
                    i18n: duplicate
                    required: false
```

and noob question:  why cannot we use basic javascript in those double brackets? like so {{fields.containerize? 'yes':'no'}} "

thanks
