### ISSUE TITLE
GitLab GraphQL Error 'committedDate' doesn't exist on type 'Commit'

### ISSUE THREAD

**Issue by Fermain** [sveltia/sveltia-cms#257]
When attempting to work with a hosted gitlab instance using PKCE and Graph API, I get this error:

```json
{
    "message": "Field 'committedDate' doesn't exist on type 'Commit'",
    "locations": [
        {
            "line": 1,
            "column": 203
        }
    ],
    "path": [
        "query",
        "project",
        "repository",
        "tree_0",
        "lastCommit",
        "committedDate"
    ],
    "extensions": {
        "code": "undefinedField",
        "typeName": "Commit",
        "fieldName": "committedDate"
    }
}
```

My config file:

```yml
local_backend: false

logo_url: /logo.svg

backend:
    name: gitlab
    branch: master
    repo: user/abc
    auth_type: pkce
    app_id: <id>
    api_root: https://gitlab.abc.com/api/v4
    base_url: https://gitlab.abc.com
    site_domain: abc.com
    auth_endpoint: oauth/authorize
    automatic_deployments: true
```

It is possible this is a misconfiguration of the instance, but I thought I would check here first to see if other users are experiencing the same issue.
