### ISSUE TITLE
i18n: Form doesn't show up

### ISSUE THREAD

**Issue by jbelien** [sveltia/sveltia-cms#258]
I have the following configuration:
```yaml
i18n:
  structure: multiple_files
  locales: [en, fr, nl, de]
  default_locale: nl

collections:
  - name: news
    label: "Latest news"
    folder: content/news
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    i18n: true
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start", name: "start", widget: "datetime" }
      - { label: "End", name: "end", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
```
and the following file structure:
```text
content/news/
├── 20240825-paragon-downtime.en.md
├── 20240825-paragon-downtime.fr.md
├── 20240825-paragon-downtime.nl.md
├── _index.en.md
├── _index.fr.md
└── _index.nl.md
```

This is what I get ; the form in English (or French, or German) just doesn't show up, only the form for the default locale shows up:
![image](https://github.com/user-attachments/assets/62e596e3-e47a-4ee8-9f99-92b3d1b3491b)

I don't see error in the console log.
And I even see that the files in the other languages are found:
![image](https://github.com/user-attachments/assets/f478906f-a0e7-43db-ba0e-c14a0d4596fa)

And I missing something or is there something not working as it should ?
Thanks already!
