### ISSUE TITLE
Datetime widget issues

### ISSUE THREAD

**Issue by jloh** [sveltia/sveltia-cms#267]
Hey all, thanks so much for creating Sveltia! I'm really enjoying it.

I'm trying to use the `datetime` widget but currently running into some issues with it dropping the timezone portion of a datetime string when saving/updating posts and having weird behaviour with the _Now_ button.

My Sveltia config for this collection looks like the below and I'm using Sveltia version `0.47.2` installed via NPM and manually initialised like this:

```javascript
window.CMS_MANUAL_INIT = true;
import CMS, { init } from "@sveltia/cms";
init();
```

Config:

```yaml
micro:
  name: "micro"
  label: "Micro"
  icon: note_stack
  folder: "content/micro"
  slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}"
  summary: "{{date | date('YYYY-MM-DD h:mm a')}} - {{body | truncate(60, '&hellip;')}}"
  create: true
  fields:
    - { label: "Title", name: "title", widget: "datetime", default: "{{now}}", format: "YYYY-MM-DD HH:mm" }
    - {
        label: "Publish Date",
        name: "date",
        widget: "datetime",
        default: "{{now}}",
        format: "YYYY-MM-DDTHH:mm:ssZ",
      }
    - { label: "Tags", name: "tags", widget: "list", "default": [], label_singular: "Tag", required: false }
    - { label: "Draft", name: "draft", widget: "boolean", default: true }
    - { label: "Body", name: "body", widget: "markdown" }
```

This works _if_ I don't hit the _Now_ button on the widget. If I don't hit it, the `title` and `date` fields get rendered like this in the resulting document:

```yaml
title: 2024-12-05 00:21
date: 2024-12-05T00:21:00+11:00
```

If I hit _Now_ to update the timestamp they get rendered like this:

```yaml
title: 2024-12-05T00:17
date: 2024-12-05T00:17
```

Not quite sure if I'm doing something wrong there, I would expect them to follow the format set in my config.

I've also noticed if I update a post and _don't_ alter the timestamp it drops the timezone.

For example with the same config, if I have a document with a `date` field like this:

```yaml
date: "2024-12-04T07:31:06.000000Z"
```

Then save the document after editing the body (not touching the date fields), `date` gets updated to this:

```yaml
date: 2024-12-04T07:31:00+11:00
```

Which in this case since it moves from UTC to my current timezone means the posts time drastically changes.

Again, thanks for Sveltia. I really love it, the UI is nice and its really fast. Let me know what I can do to help debug.
