### ISSUE TITLE
Date in entry slug is not UTC but local

### ISSUE THREAD

**Issue by laril** [sveltia/sveltia-cms#278]
In my setup the posts ase saved using this slug:
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}" 

In Decap cms I get files which are using UTC timezone, but it seems that Sveltia is now using local timezone. This now causes for me other issues as the website code expects the times in urls to be specified in UTC. 

I don't think I previously had the some problem even with Sveltia, so has something related to this changed in Sveltia?

**Comment by kyoshino** [comment]
Will check.

**Comment by kyoshino** [comment]
I don’t think I have made a change to Sveltia CMS but can confirm the bug. The fix is coming right away.

**Comment by kyoshino** [comment]
Fixed in [v0.49.5](https://github.com/sveltia/sveltia-cms/releases/tag/v0.49.5) 🙇🏼

**Comment by jloh** [comment]
Hey @kyoshino I just tried this in v0.51.1 and the `slug` was still created in local TZ, not UTC. `date` for my notes is configured like this:

```yaml
- {
    label: "Publish Date",
    name: "date",
    widget: "datetime",
    default: "{{now}}",
    format: "YYYY-MM-DDTHH:mm:ssZ",
    picker_utc: false,
}
```

And slug is like this:

```yaml
path: "{{year}}/{{slug}}"
slug: "{{date | date('YYYY-MM-DD_HHmm')}}"
```

Does `date` need to be set to UTC for this to work?

Can open a new issue if thats easier, apologies for posting on an old one.
