### ISSUE TITLE
`relation` widget doesn't work with collections containing only one item

### ISSUE THREAD

**Issue by blu3id** [sveltia/sveltia-cms#300]
The `relation` widget doesn't work when the collection if references only contains one item. The displayed widget lists `{{relation.*.name}}` rather than the item in the collection (the value also doesn't work). But if there is more than one item in the referenced collection it works as expected. e.g in the minimal test case below if you change `data/relation.yaml` to the following everything works:

```yaml
- name: Single Item
- name: Second Item
```

The following is a minimal test case `config.yml` and associated files:

`config.yml`
```yaml
backend:
  name: github
  repo: user/repo
  branch: main

media_folder: public/assets/uploads
public_folder: /assets/uploads

collections:
  - name: collection
    label: Collection
    folder: content/pages
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Relation",
          name: "relation",
          widget: "relation",
          collection: "data",
          file: "relation",
          search_fields: ["relation.*.name"],
          display_fields: ["relation.*.name"],
          value_field: "relation.*.name",
        }

  - name: data
    label: Confiuration
    icon: settings
    files:
      - name: relation
        label: Relation Data 
        file: data/relation.yaml
        fields:
          - name: relation
            label: Relation Data
            widget: list
            root: true
            fields:
              - {
                  label: "Name",
                  name: "name",
                  widget: "string",
                }
```

`content/pages/test.md`
```markdown
---
title: Test Page
relation: Single Item
---

```

`data/relation.yaml`
```yaml
- name: Single Item

```
