### ISSUE TITLE
Changing the default sort on Admin UI page

### ISSUE THREAD

**Issue by alexpetralia** [sveltia/sveltia-cms#304]
Hello, thank you for all your work here! Setup was very simple thanks to your docs.

I just had one quick question: in the Admin UI page, is it possible to set a `default` sort field? 

I see in the [Decamp CMS config](https://decapcms.org/docs/configuration-options/) that we can specify fields which are sortable, but not necessarily one for which to be the default sort (e.g. last_modified DESC).

**Comment by kyoshino** [comment]
Hiya! Actually, Static CMS, a now-discontinued Netlify CMS fork, has altered the `sortable_fields` option to include the default sort field and direction. I’m thinking about adding compatibility for it. Will work on it shortly.

- Netlify/Decap CMS: https://decapcms.org/docs/configuration-options/#sortable_fields
- Static CMS: https://staticjscms.netlify.app/docs/collection-overview#sortable-fields

This is the relevant Netlify/Decap CMS issue:

- https://github.com/decaporg/decap-cms/issues/3715

**Comment by kyoshino** [comment]
The extended `sortable_fields` option is shipped with [v0.54.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.54.0).

**Comment by alexpetralia** [comment]
Amazing, thank you so much!! This is awesome.

**Comment by alexpetralia** [comment]
Hi @kyoshino I attempted to apply this code change to my `config.yml` but don't seem to be getting the intended results.

Here is the relevant section of my `admin/config.yml`:

```
collections:
  - name: 'Posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{date}} - {{title}} [{{tags}}]'
    editor:
      preview: true
    display_fields: [title, date]
    sortable_fields: 
      fields: [title, date]
      default:
        field: date
        direction: descending
```

I can see that in my `_posts` frontmatter I use the field `date`. However, when I open up the Admin page (http://localhost:4000/admin/index.html#/collections/Posts), the posts are still not sorting by `date: descending`.  I need to click "Publish Date, new to old" in order to correct it.

![Image](https://github.com/user-attachments/assets/e136c189-ff48-40fa-b7c3-85de975d9628)

I can see I am on the newest release: https://unpkg.com/@sveltia/cms@0.55.0/dist/sveltia-cms.js. I also tried using `published_date` instead of `date` but that did not work either.

Do you see anything at first glance I'm doing incorrectly here?

Thanks,
Alex
