### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AntoineBx** [sveltia/sveltia-cms#314]
Hello kyoshino! I have an error when opening collection files and idk why

![Image](https://github.com/user-attachments/assets/430058f8-badf-4f85-b9dc-636141f3b6a5)

Even when i reduce my config to this, i still cannot open logo without this error 
I get the same error on dev or in production
```
backend:
  name: gitlab
  repo: ...
  auth_type: pkce
  app_id: ...
  publish_mode: editorial_workflow
  branch: main
  automatic_deployments: false
load_config_file: false
media_folder: public/img
public_folder: /img
i18n:
  structure: multiple_folders
  locales:
    - en
  default_locale: en
collections:
  - label: Global Options
    name: options
    i18n: true
    editor:
      preview: false
    files:
      - label: logo
        name: logo
        i18n: true
        file: content/_data/{{locale}}/logo.yml
        fields:
          - label: Logo
            name: logo
            widget: string
            i18n: true
_siteURL: http://localhost:3000
_baseURL: http://localhost:3000
```

Thanks in advance
