### ISSUE TITLE
Bug with internationalized variable types field

### ISSUE THREAD

**Issue by greatislander** [sveltia/sveltia-cms#336]
I've encountered a very specific edge case related to variable types object fields with internationalization support. I have a use case where items managed by the CMS can either be a page on the site or a link to an external URL. To facilitate this for content editors I've used one of the recommended approaches for [conditional fields](https://github.com/sveltia/sveltia-cms#:~:text=The%20Object%20widget%20supports%20variable%20types%20(the%20types%20option)%20just%20like%20the%20List%20widget.) and created an [Object widget with a variable type](https://github.com/greatislander/sveltia-cms-localization/blob/c9f259573093fefc6cbb02e400114841874a7110/config.yml#L33-L53) which allows content editors to enter _either_ the slug used for a local page _or_ an external link:

```yaml
      - label: Link
        name: link
        widget: object
        i18n: duplicate
        required: true
        types:
          - label: Slug
            name: slug
            fields:
              - label: Slug
                name: slug
                widget: string
                i18n: true
          - label: External Link
            name: link
            fields:
              - label: Link
                name: link
                widget: string
                type: url
                i18n: duplicate
```

The bug seems to be caused by the fact that there is a nested field named `slug` within the object. When I add a translation of the content, I can enter the translated slug. But when I save, the entire object is saved as a null value:

https://github.com/user-attachments/assets/7862fdb3-0089-4f10-b404-5f5fa9e3217b

If I change that field name to anything else it works as I would expect (the object is saved in the translated page).

I assume this is an edge case related to the role that `slug` plays within the file system management. I could change the name of the field but I'm wondering if this is fixable? Totally understand if it's not a priority though. Thanks in advance!
