### ISSUE TITLE
Relation field issue when value_field on related collection item is called 'slug'

### ISSUE THREAD

**Issue by greatislander** [sveltia/sveltia-cms#351]
I have run into an issue with the relation field. I have a collection called `projects` which includes the following configuration for a field called `slug` that lets content editors customize the URL-safe slug for the project:

```yml
      - label: Slug
        name: slug
        widget: string
        i18n: true
        required: true
        hint: Use this field to customize the URL of the project. For example, if you want your project's URL to be `/projects/example/`, enter `example`.
```

I'm running into an issue with another collection with a relation field to `projects` configured as follows:

```yml
      - label: Parent Project
        name: parent
        widget: relation
        collection: projects
        value_field: slug
        search_fields: [title]
        display_fields: [title]
        required: true
```

My expectation would be that this field would store the `slug` field from the related project; however, it instead stores the file slug. So if I have a project where the title is `Example Project`, the filename is `example-project.md`, and the slug field is `example`, if I select it using the relation field the stored value is `example-project`, not `example`.
