### ISSUE TITLE
Support for OAuth 2 and OpenID

### ISSUE THREAD

**Issue by ajmas** [sveltia/sveltia-cms#354]
It would be good to be able to specify any OAuth2 or OpenID service for authentication and then be able to pass that token to the backend that the user has configured.

Maybe using something equivalent to [vue-authenticate-2](https://www.npmjs.com/package/vue-authenticate-2)? This would make it easier to configure with 'private' auth gateways and git repos.

Maybe with a config such as:

```yml
backend:
  name: 'github'
  repo: 'owner/repo'
  branch: 'main'
  auth:
    - module: 'openid-auth'
    - type: openid
    - provider: openid
    - url: https://accounts.example.com
    - realm: isekai
    - clientId: in-another-world
```
