### ISSUE TITLE
Multiple configuration files do not work with YAML anchors and aliases

### ISSUE THREAD

**Issue by benabraham** [sveltia/sveltia-cms#356]
Tried to use [Multiple configuration files](https://github.com/sveltia/sveltia-cms#providing-multiple-configuration-files) with YAML anchors and aliases.

It doesn't work if the definition and usage are not in the same file.

definiton example
```yaml
whatever_here: &datetime__date
  - widget: datetime
    time_format: false
    date_format: YYYY-MM-DD
    format: YYYY-MM-DD
```
usage example
```yaml
fields:
  - name: Date
    <<: *datetime__date
```

P.S.: It was a refactor from existing and working config.
