### ISSUE TITLE
CMS not load when published, but local test is ok.

### ISSUE THREAD

**Issue by 8ar10der** [sveltia/sveltia-cms#370]
Hi, I just deployed sveltia-cms with sveltia-cms-auth. Everything works when I preview the site at local. However, the /admin can be access but just an empty page when I pushed to the remote. The browser devtool console no any error message. And I can confirm the js script be loaded after I checked the "Network" requests, just not display.

Anybody could help me check it?

My site is: https://dev.amao.run
My site architecture: Hugo + Cloudflare page + github backend + sveltia-cms + sveltia-cms-auth
My sveltia-cms files:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Content Manager</title>
    <!-- Include the script that enables Netlify Identity on this page. -->
    <!-- <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script> -->
  </head>
  <body>
    <!-- Include the script that builds the page and powers Decap CMS -->
    <script src="https://unpkg.com/@sveltia/cms/dist/sveltia-cms.js"></script>
  </body>
</html>
```
```yaml
backend:
  name: github
  repo: 8ar10der/MyTechBlog
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.tigersui.workers.dev
media_folder: static/img
public_folder: /img
collections:
  - name: '中文博客'
    label: '中文博客'
    folder: 'content/zh-cn/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'ToC', name: 'toc', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: '英文博客'
    label: '英文博客'
    folder: 'content/en/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'ToC', name: 'toc', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```
