### ISSUE TITLE
Strange behaviour when adding a video via the file widget

### ISSUE THREAD

**Issue by captainharrie** [sveltia/sveltia-cms#371]
Hiya! I'm trying to get set up with Sveltia at the moment, and adding a video file to the file widget causes half the page to be taken up by an invisible video element, making the CMS completely unusable:

![Image](https://github.com/user-attachments/assets/fbd312f2-ede9-4ea8-aa9a-78ae6f0eca74)
![Image](https://github.com/user-attachments/assets/2f7ab111-ab27-4d59-a3a2-90405ddd7d85)

& it repeatedly adds video elements each time you open the post with the video in it:
![Image](https://github.com/user-attachments/assets/7fc33557-d2fd-4963-8857-506c3e7cecaf)

I don't think I've set things up incorrectly here but just to be certain, here is my current config for blog posts:

```yaml
collections:
  - name: "blog"
    label: "Posts"
    label_singular: "Post"
    folder: "src/posts"
    create: true
    slug: "{{body | truncate(60, '***')}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", hint: "Enter tags separated by a comma", required: false }
      - label: "Video"
        name: "video"
        widget: "file"
        required: false
        media_library:
          allow_multiple: false
      - label: "Image"
        name: "galleryImages"
        widget: "list"
        summary: "{{fields.image}}"
        required: false
        fields: 
        - {label: Image, name: image, widget: image}
        - { label: "Image Alt Text", 
          hint: "Imagine describing the image in a short sentence to someone in the other room. [Refer to this infographic for guidance](https://i0.wp.com/veroniiiica.com/wp-content/uploads/2018/01/capybara_alt_text.png?w=596&ssl=1)!", name: "imageAltText", widget: "string"}
        - label: "Column Size"
          name: "colsize"
          widget: "number"
          default: 1
          value_type: "int"
          min: 1
          max: 3
          step: 1
      - { label: "Body", name: "body", widget: "markdown" }
```

In the screenshots above I'm testing locally in Chrome, but I was originally testing in Edge due to Firefox being my typical browser. Having just set up the authentication, I can also confirm it happens in the live version in Firefox, so neither the browser nor the local/live state appears to affect anything here.
