### ISSUE TITLE
authors and tags relation widget no values issue

### ISSUE THREAD

**Issue by gemini0x2** [sveltia/sveltia-cms#375]
Hello @kyoshino ,  

First of all, thank you for maintaining and keeping this project alive. This is my first time setting up sveltia-cms!
I really like your project, but I'm having issues getting the relation widget to work. 

I can create new tags and the values display correctly on this page.
![Image](https://github.com/user-attachments/assets/a09c6902-6905-4c2a-8eaa-340e5c0e389a)

But when creating a new post the tags and author values are not displayed, it shows no values. only an empty radio button. 
![Image](https://github.com/user-attachments/assets/446dd89f-2892-4a6a-b2ff-4275f2b428d6)

If I select the empty button it will assign the value "authors" and "tags", which do not exists in the meta files.
![Image](https://github.com/user-attachments/assets/697f5b38-0d92-46e9-a721-8f632e168e06)

This causes the deployment to fail, as is not assigning the correct relation values.
Error:
```shell
12:16:13 AM: > Build error occurred
12:16:13 AM: Error: slug field not match with the path of its content source
12:16:13 AM:     at /opt/build/repo/.next/server/pages/posts/tags/[[...slug]].js:741:13
12:16:13 AM:     at Array.map (<anonymous>)
12:16:13 AM:     at fetchPostContent (/opt/build/repo/.next/server/pages/posts/tags/[[...slug]].js:724:68)
12:16:13 AM:     at countPosts (/opt/build/repo/.next/server/pages/posts/tags/[[...slug]].js:757:10)
12:16:13 AM:     at /opt/build/repo/.next/server/pages/posts/tags/[[...slug]].js:1290:68
12:16:13 AM:     at Array.flatMap (<anonymous>)
12:16:13 AM:     at getStaticPaths (/opt/build/repo/.next/server/pages/posts/tags/[[...slug]].js:1289:52)
12:16:13 AM:     at buildStaticPaths (/opt/build/repo/node_modules/next/dist/build/utils.js:16:86)
12:16:13 AM:     at /opt/build/repo/node_modules/next/dist/build/utils.js:26:628
12:16:13 AM:     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
12:16:13 AM:   type: 'Error'
12:16:13 AM: }
12:16:13 AM: 
```

For the frontend I'm using this [template](https://github.com/wutali/nextjs-netlify-blog-template). 

**Here is my setup:**

config.yml
```yml
backend:
  name: github
  repo: gemini0x2/myrepo
  branch: master # or main
  base_url: https://myurl.app
  auth_endpoint: oauth/authorize
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"
```

authors.yml
```yml
authors:
  - slug: david
    name: David
    introduction:
      likes to read
```

tags.yml
```yml
tags:
  - slug: document
    name: document
  - slug: mock
    name: mock
  - slug: style
    name: style
  - slug: license
    name: license
  - slug: mdx
    name: mdx
  - slug: markdown
    name: markdown
```

I hope you can help me with this issue, thank you so much!
