### ISSUE TITLE
Date format generated by Sveltia isn't recognized by Hugo

### ISSUE THREAD

**Issue by msfjarvis** [sveltia/sveltia-cms#382]
I just wrote out a post using the CMS which did not show up on my built Hugo site, the culprit ended up being the date format: https://github.com/msfjarvis/msfjarvis.dev/commit/38780782ca26bb8d6671c7f20c4bf5a2f2a46f4c .

My Sveltia config is here: https://github.com/msfjarvis/msfjarvis.dev/blob/38780782ca26bb8d6671c7f20c4bf5a2f2a46f4c/static/admin/config.yml

**Comment by kyoshino** [comment]
Interesting, will check.

**Comment by kyoshino** [comment]
No idea how it could have happened. I still get the `.000` suffix with your config:

```toml
date = 2025-04-23T09:41:00.000
lastmod = 2025-04-23T09:42:00.000
```
