### ISSUE TITLE
TOML format output in .md files missing delimiters and incorrect body placement

### ISSUE THREAD

**Issue by baditaflorin** [sveltia/sveltia-cms#396]
When Sveltia CMS is configured for a collection using format: toml and extension: "md", the generated .md files are missing the required +++ front matter delimiters. Additionally, the content designated for the main body (using a field like body with widget: markdown) is incorrectly included as a body = "..." key-value pair within the front matter section, instead of being placed after the closing delimiter.

This results in files that are not correctly parsed by Hugo (or other static site generators expecting standard front matter separation), causing the front matter to be rendered as plain text on the resulting page.

To Reproduce

Configure a collection in config.yml with format: toml and extension: "md". Ensure there's a field named body with widget: markdown. (See example config below).
Use the Sveltia CMS admin interface to create a new entry in this collection, filling in the title, date, description, and body fields.
Save the entry.
Inspect the raw .md file created in the Git repository.
Expected behavior
The created .md file should have the following structure:

```Markdown

+++
title = "Example Title"
date = "2025-05-08T10:00:00Z"
description = "Example description"
# Other front matter fields...
+++

This is the content entered into the body field.
```
It should appear *after* the closing front matter delimiter.
Actual behavior
The created .md file incorrectly looks like this (missing delimiters, body included as a key-value pair):
```
title = "Example Title"
date = "2025-05-08T10:00:00Z"
description = "Example description"
# Other front matter fields...
body = "This is the content entered into the body field."
CMS configuration (config.yml snippet)
```

```YAML

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: toml # Specifies TOML for front matter
    extension: "md" # Specifies .md file extension
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"} # Main content field
 ```

### Applicable Versions:

Sveltia CMS Version: https://unpkg.com/@sveltia/cms/dist/sveltia-cms.js
Browser: Chrome on MacOS
Git Backend: GitHub (using Sveltia Authenticator via Cloudflare Worker)
SSG: Hugo

### Additional context
This issue prevents Hugo from correctly parsing the content files created by the CMS when TOML format is selected. The authentication and basic file creation seem to work, but the file content structure is incorrect for TOML front matter in Markdown files.
