### ISSUE TITLE
Field content for an image points to `media_folder` instead of `public_folder`

### ISSUE THREAD

**Issue by oliverrahner** [sveltia/sveltia-cms#397]
According to [decap docs](https://decapcms.org/docs/configuration-options/#media-and-public-folders):

> select an image called philosoraptor.png, the image would be saved to the repository at /static/images/uploads/philosoraptor.png, and the avatar field for the file would be set to /images/uploads/philosoraptor.png.

In my repository, the image is saved at the correct spot (--> `media_folder`), but the field entry is `/static/images/uploads/philosoraptor.png`, instead of the correct `public_folder` URL `/images/uploads/philosoraptor.png`.

This is my config (I know that auth won't work yet 😅):

```
local_backend: true

backend:
  name: github
  branch: main
  repo: oliverrahner/dummy_name
media_folder: "/public"
public_folder: "/"
locale: de
collections:
- name: "vehicles"
  label: "Fahrzeuge"
  label_singular: "Fahrzeug"
  folder: "data/vehicles/"
  identifier_field: id
  format: json
  create: true
  summary: "{{disabled | ternary('🚫', '')}} {{name}}"
  media_folder: "/public/assets/images/{{slug}}"
  public_folder: "/assets/images/{{slug}}"
  icon: airport_shuttle

  fields:
  - { name: "name", label: "Bezeichnung", widget: "string" }
  - { name: "disabled", label: "Deaktiviert", widget: "boolean", required: false }
  - { name: "id", label: "Kurzname", widget: "string" }
  - name: "type"
    label: "Typ"
    widget: "select"
    options:
    - Campervan
    - Wohnwagen
    - Teilintegriert
  - { name: "platform", label: "Plattform", widget: "string", required: false }
  - { name: "description", label: "Beschreibung", widget: "text", required: false }
  - { name: "dimensions", label: "Abmessungen", widget: "string", required: false, default: "L/B/H xxx/xxx/xxx cm" }
  - { name: "seats", label: "Sitzplätze", widget: "number", required: false }
  - { name: "beds", label: "Schlafplätze", widget: "string", required: false }
  - { name: "cooling", label: "Kühlung", widget: "string", required: false }
  - { name: "load_weight", label: "Zuladung", widget: "string", required: false }
  - { name: "max_weight", label: "Maximal zul. Gesamtgewicht", widget: "string", required: false }
  - { name: "tow_weight", label: "Anhängelast", widget: "string", required: false }
  - { name: "water_volume", label: "Wasservolumen", widget: "string", required: false }
  - { name: "air_circulation", label: "Luftzirkulation", widget: "string", required: false }
  - { name: "bike_carrier", label: "Fahrradträger", widget: "string", required: false }
  - { name: "awning", label: "Markise", widget: "boolean", required: false }
  - { name: "rear_cam", label: "Rückfahrkamera", widget: "boolean", required: false }
  - { name: "solar", label: "Solar", widget: "string", required: false }
  - { name: "infotainment", label: "Infotainment", widget: "string", required: false }
  - { name: "price_high", label: "Preis Hauptsaison", widget: "string", required: false }
  - { name: "price_mid", label: "Preis Zwischensaison", widget: "string", required: false }
  - { name: "price_low", label: "Preis Nebensaison", widget: "string", required: false }
  - { name: "price_winter", label: "Preis Winter", widget: "string", required: false }
  - { name: "image_main", label: "Hauptbild", widget: "image", choose_url: false, required: false }
  - name: "images_detail"
    label: "Detailbilder"
    label_singular: "Detailbild"
    widget: "list"
    field:
    - label: "Bild"
    - name: "image"
    - widget: "image"
    - choose_url: false
    required: false

- name: "selling-offers"
  label: "Verkaufangebote"
  label_singular: "Verkaufangebot"
  folder: "data/selling-offers/"
  identifier_field: id
  format: json
  create: true
  summary: "{{disabled | ternary('🚫', '')}} {{title}}"
  media_folder: "/public/assets/images/{{slug}}"
  public_folder: "/assets/images/{{slug}}"
  icon: sell

  fields:
  - { name: "title", label: "Bezeichnung", widget: "string" }
  - { name: "disabled", label: "Deaktiviert", widget: "boolean", required: false }
  - { name: "id", label: "Kurzname", widget: "string" }
  - { name: "price", label: "Preis", widget: "number" }
  - { name: "mainImage", label: "Hauptbild", widget: "image", choose_url: false, required: false }
  - { name: "additionalImages", label: "Zusätzliche Bilder", label_singular: "Zusätzliches Bild", widget: "list", field: { label: "Bild", name: "image", widget: "image", choose_url: false }, required: false }
  - { name: "description", label: "Beschreibung", widget: "markdown", required: false }
```
