### ISSUE TITLE
`field:` of `widget: list` not working in newLine

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#40]
if `field:` is placed in newLine as `- { ... }` its content 
- vanishes when a new element is added by the button
- does not get saved correctly

I'm not sure if this is a sveltia-bug, wrong config (not catched) or a problem with YAML-definition

**Comment by kyoshino** [comment]
I _think_ it’s a misconfiguration. For the [list widget](https://decapcms.org/docs/widgets/#list), `fields` is an array but `field` is an object, so the `-` (a list marker) is unnecessary. Your choice would be either

```yaml
widget: list
fields:
 - { name: image, label: Image, widget: image }
```

or

```yaml
widget: list
field: { name: image, label: Image, widget: image }
```
