### ISSUE TITLE
Upload images to global assets, images will be stored in the base/root repo. media_folder: "static/uploads" is ignored

### ISSUE THREAD

**Issue by husenunicorn** [sveltia/sveltia-cms#405]
Here is my config.yml 

```yml
backend:
  name: github
  repo: 
  branch: master # Branch to update (optional; defaults to master)
  base_url: 

logo_url: /admin/1000060484.svg

i18n:
  structure: multiple_files
  locales: [id, en, ja, de, ko, fr]
  default_locale: id
  initial_locales: default
  save_all_locales: false
  omit_default_locale_from_filename: true

output:
  omit_empty_optional_fields: true

media_folder: "static/uploads"
public_folder: "/uploads"

media_libraries:
  stock_assets:
    providers: []
  default:
    config:
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
        svg:
          optimize: true

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: posts
    label: Posts
    label_singular: "Post"
    folder: content/posts
    create: true
    delete: false
    i18n: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    extension: "md"
    format: "toml-frontmatter"
    slug: "{{slug}}"
    editor:
      preview: false
    thumbnail: "*.feature_image"
    summary: "{{title | truncate(50)}} - {{date | date('lll')}}"
    sortable_fields:
      fields: [title, date]
      default:
        field: date
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        minlength: 30
        hint: "SEO Recommended: 60 characters"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "text"
        minlength: 70
        hint: "SEO Recommended: 145 characters"
        required: true
        i18n: true
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        format: "YYYY-MM-DDTHH:mm:ss"
        picker_utc: false
        required: false
        i18n: duplicate
      - label: "Updated Date"
        name: "updated"
        widget: "datetime"
        default: "{{now}}"
        format: "YYYY-MM-DDTHH:mm:ss"
        picker_utc: false
        required: false
        i18n: duplicate
      - label: "Feature Image & Featured"
        name: "extra"
        widget: "object"
        collapsed: false
        summary: "Feature Image & Featured"
        i18n: true
        fields:
          - label: "Feature Image"
            name: "feature_image"
            widget: "image"
            required: true
            choose_url: false
            allow_multiple: false
            i18n: duplicate
            hint: "Mohon Upload Gambar di Entry Assets!"
          - label: "Image caption"
            name: "feature_image_caption"
            widget: "string"
            required: false
            i18n: true
            hint: "Jika kosong, secara otomatis akan menggunakan Title untuk image caption"
          - label: "Featured"
            name: "featured"
            widget: "boolean"
            default: false
            i18n: true
            hint: "Jika True Artikel akan di pin di tab Featured"
          - label: "Reaction"
            name: "reaction"
            widget: "boolean"
            default: false
            i18n: duplicate
          - label: "Related"
            name: "related"
            widget: "string"
            required: false
            i18n: true
      - label: "Tag & Author"
        name: "taxonomies"
        widget: "object"
        collapsed: false
        summary: "Tag & Author"
        i18n: true
        fields:
          - lable: "Tag"
            name: "tag"
            widget: "select"
            multiple: true
            min: 1
            max: 3
            required: true
            hint: "Min 1 & Max 3"
            options: ["a", "b", "c", "d", "e", "f"]
            i18n: duplicate
          - lable: "Author"
            name: "author"
            widget: "select"
            multiple: true
            min: 1
            required: true
            hint: "Min 1"
            options: ["a", "b"]
            i18n: duplicate
      - label: "Posts content"
        name: "body"
        widget: "markdown"
        required: true
        i18n: true
```
When uploading images to global assets (Sveltia v0.76.0-v0.77.0), the images will be stored in the base/root repo, the global asset settings in the media_folder do not work. (I uploaded a cloud image in the static/upload folder without using Sveltia CMS. But the image appears)

![Image](https://github.com/user-attachments/assets/7a06a35d-d382-4be5-848f-1722830523c4)

![Image](https://github.com/user-attachments/assets/380f728a-1382-43ea-a432-abf7c5890cc7)

When uploading images to uncategorized (Sveltia v0.75.0) it works correctly 

![Image](https://github.com/user-attachments/assets/77b2e025-d07b-4f06-bcaf-8e7d739b28a0)
![Image](https://github.com/user-attachments/assets/d7ff8d6e-c686-4c13-916c-e9b76d09259e)

I think this has something to do with this update: #390 

And is it possible that when creating a new draft entry for an image widget the image assets in all post entries are not displayed except the image on the global asset? Only show the uploaded image in the draft entry and show the no files found if the image has not been uploaded.
