### ISSUE TITLE
public_folder - remove insistence of a forward slash

### ISSUE THREAD

**Issue by mimecine** [sveltia/sveltia-cms#406]
I have an issue where I want all my images to be served and optimized by Astro. 
A file in frontmatter can be resolved with an absolute path, but inside markdown content an absolute path means it will be served from outside Astro processing. 

I don't quite understand why the public_folder option necessarily needs to start with a forward slash? 

If I try to set public_folder: '../../assets/img' I get a complaint. 

Incidentally I can set it to '@assets/img' and make use of import aliases in typescript, but I feel as a generic CMS the choice of how to output the string should be the developer's.

**Comment by husenunicorn** [comment]
Have you used netlify/decap cms before? Sveltia CMS follows the rules that netlify/decap CMS uses and a few improvements.

You can leave the public_folder value empty in collections, it will store the image in the draft entry asset created.


```yml
media_folder: static/media
public_folder: /media
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
      - label: Title
        name: title
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
```

inside the frontmatter will be written 

+++
image = "image-name-wants-optimized.png"
+++

Next, just adjust it to the framework you are using.

post.html

```html
{% set img_path = page.path ~ page.image %}

{% set img_m = resize_image(path=img_path, width=1600, op="fit_width", format="webp", quality=80) %}

<img
  class="medium"
  src="{{ img_m }}"
  alt="{{ page.title }}" />
```

https://decapcms.org/docs/collection-folder/
