### ISSUE TITLE
There is an error on Select widget

### ISSUE THREAD

**Issue by husenunicorn** [sveltia/sveltia-cms#415]
```yml
- label: "Tag & Author"
        name: "taxonomies"
        widget: "object"
        collapsed: false
        summary: "Tag & Author"
        i18n: true
        fields:
          - lable: "Tag"
            name: "tag"
            widget: "select"
            multiple: true
            min: 1
            max: 3
            required: true
            hint: "Min 1 & Max 3"
            options: ["a", "b", "c", "d", "e", "f"]
            i18n: duplicate
          - lable: "Author"
            name: "author"
            widget: "select"
            multiple: true
            min: 1
            required: true
            hint: "Min 1"
            options: ["a", "b"]
            i18n: duplicate
```

![Image](https://github.com/user-attachments/assets/37344ca5-6cde-4a42-9d06-2e8746be065c)

1. Create a new draft entry
2. select tag & author
3. Refresh the CMS page
4. Select restore then click save

Then the error will appear as in the picture, to be able to save deselect and then select again and click save.
