### ISSUE TITLE
Add option to slugify assets filenames

### ISSUE THREAD

**Issue by ayamflow** [sveltia/sveltia-cms#422]
Hello!
Haven't had the chance to thank you yet for your work & dedication to this project. I chose sveltia for a low-carbon & pro-bono project as it fits the bill perfectly. 🙏

## What
Uploaded images filenames are not sanitized.

I cannot tell if my config.yml is incomplete or if the feature is missing. It seems like it's implemented in decapcms, see here: https://github.com/decaporg/decap-cms/pull/1135

My expectation is that any image upload should get sanitized, following the `slug.encoding`& `slug.clean_accents` rules. However it's not happening - spaces, accents & other characters are left in the image filename. Am I missing something ?

Additionally, a way to automatically rename images (with a template ? for instance `{{collection}}-{{datetime}}` would be awesome.

## Why
There are a few reasons, the main ones being anonymizing the filename, and avoiding any issue with hosting not handling accents properly.

**Comment by kyoshino** [comment]
This is intentional, actually. As reported in https://github.com/decaporg/decap-cms/issues/4288, Netlify/Decap CMS has no control over asset filenames, so we have decided not to alter the asset names. The entry [`slug`](https://decapcms.org/docs/configuration-options/#slug-type) option added in https://github.com/decaporg/decap-cms/pull/1135 doesn’t apply to asset filenames.

But you’re making a good point! There was a discussion about it recently in #404, and I’m planning to add an option to apply the `slug` option to asset filenames as well. Will work on it sometime this week or next.

**Comment by kyoshino** [comment]
Templatizing asset filenames is discussed in

- https://github.com/decaporg/decap-cms/issues/857

**Comment by ayamflow** [comment]
Great to hear ! Thank you for the swift reply.

**Comment by kyoshino** [comment]
The new option added in [v0.81.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.81.0). I’ll work on filename templates later.

**Comment by jakobzudrell** [comment]
this doesn't seem to work for me... files are still uploaded with their original filename.

```yaml
media_libraries:
  default:
    config:
      max_file_size: 1024000
      slugify_filename: true
      transformations:
```
I tested it with the exact given sample in the README...

This is a collection I'm testing:
```yaml
  - name: "tracks"
    label: "Tracks"
    folder: "content/tracks"
    slug: "{{uuid_shorter}}"
    index_file:
      name: _index
      fields:
        - { label: "Description", name: "description", widget: "string" }
      editor:
        preview: false
    create: true
    media_folder: /static/media/gpx
    public_folder: /media/gpx
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: GPX file
        name: gpx_file
        widget: "file"
        accept: ".gpx"
        media_library:
          config:
            slugify_filename: true
```

Any ideas? :)

**Comment by kyoshino** [comment]
@jakobzudrell I cannot reproduce the issue with a quick local test. Please file a new issue with sample filenames included.

**Comment by kyoshino** [comment]
As the [README](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#better-asset-management) says, slugification is done according to the global `slug` option.

> If you want to slugify filenames according to the [`slug` option](https://decapcms.org/docs/configuration-options/#slug-type), use the `slugify_filename` [default media library option](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#configuring-multiple-media-libraries).

it means non-ASCII characters and accents are allowed in the filenames by default. You can just add the following to your `config.yml` to change the behaviour:

```yaml
slug:
  encoding: ascii
  clean_accents: true
```

Then, this will also work:

> When the `clean_accents` option is enabled for [entry slugs](https://decapcms.org/docs/configuration-options/#slug-type), certain characters, such as German umlauts, will be [transliterated](https://en.wikipedia.org/wiki/Transliteration).

**Comment by jakobzudrell** [comment]
thanks for your replies @kyoshino !

The `slug` option is present in my case.

![Image](https://github.com/user-attachments/assets/4672f335-74b9-4dfa-b4f1-a58bbda9e342)

Here the (truncated) config:
```yaml
media_folder: "static/media"
public_folder: "/media"

media_libraries:
  default:
    config:
      slugify_filename: true

slug:
  encoding: ascii
  clean_accents: true

collections:
   - name: "tracks"
    label: "Tracks"
    folder: "content/tracks"
    slug: "{{uuid_shorter}}"
    index_file:
      name: _index
      fields:
        - { label: "Description", name: "description", widget: "string" }
      editor:
        preview: false
    create: true
    media_folder: /static/media/gpx
    public_folder: /media/gpx
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "track" }
      - label: GPX file
        name: gpx_file
        widget: "file"
        accept: ".gpx"
```

According to my understanding, this should result in the file also being renamed to a short uuid, which it doesn't..
