### ISSUE TITLE
The select widget is not duplicated in the translated content entry and when saved there is no value. “i18n: duplicate” & "required: true" is ignored

### ISSUE THREAD

**Issue by husenunicorn** [sveltia/sveltia-cms#427]
Here is the configuration I used
```yml
backend:
  name: github
  repo: 
  branch: master # Branch to update (optional; defaults to master)
  base_url: 
  automatic_deployments: true

logo_url: /admin/admin.jpg

i18n:
  structure: multiple_files
  locales: [id, en, ja, ko, fr, de]
  default_locale: id
  initial_locales: default
  save_all_locales: false
  omit_default_locale_from_filename: true

output:
  omit_empty_optional_fields: true

media_folder: "static/uploads"
public_folder: "/uploads"

media_libraries:
  stock_assets:
    providers: []
  default:
    config:
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
        svg:
          optimize: true

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: posts
    icon: post
    label: Posts
    label_singular: "Post"
    folder: content/posts
    create: true
    delete: false
    i18n: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    extension: "md"
    format: "toml-frontmatter"
    slug: "{{slug}}"
    editor:
      preview: true
    thumbnail: "*.feature_image"
    summary: "{{title | truncate(50)}} - {{date | date('lll')}}"
    sortable_fields:
      fields: [title, date]
      default:
        field: date
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        # minlength: 30
        hint: "SEO Recommended: **60 characters**"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "text"
        # minlength: 70
        hint: "SEO Recommended: **145 characters**"
        required: true
        i18n: true
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        format: "YYYY-MM-DDTHH:mm:ss"
        picker_utc: false
        required: false
        i18n: duplicate
        readonly: true
      - label: "Updated Date"
        name: "updated"
        widget: "datetime"
        default: "{{now}}"
        format: "YYYY-MM-DDTHH:mm:ss"
        picker_utc: false
        required: false
        i18n: true
      - label: "Feature Image & Featured"
        name: "extra"
        widget: "object"
        collapsed: false
        summary: "Feature Image & Featured"
        i18n: true
        fields:
          - label: "Feature Image"
            name: "feature_image"
            widget: "image"
            required: true
            choose_url: false
            allow_multiple: false
            i18n: duplicate
            hint: "**Mohon Upload Gambar di Entry Assets!**"
          - label: "Image caption"
            name: "feature_image_caption"
            widget: "string"
            required: false
            i18n: true
            hint: "Jika kosong, secara otomatis akan menggunakan Title untuk image caption"
          - label: "Featured"
            name: "featured"
            widget: "boolean"
            default: false
            i18n: true
            hint: "Jika True Artikel akan di pin di tab Featured"
          - label: "Related"
            name: "related"
            widget: "string"
            required: false
            i18n: true
            hint: "**Topik Artikel yang terkait**"
      - label: "Tag & Author"
        name: "taxonomies"
        widget: "object"
        collapsed: false
        summary: "Tag & Author"
        i18n: true
        fields:
          - lable: "Tag"
            name: "tag"
            widget: "select"
            multiple: true
            min: 1
            max: 3
            required: true
            hint: "Min 1 & Max 3"
            options: ["a", "b", "c", "d", "e", "f"]
            i18n: duplicate
          - lable: "Author"
            name: "author"
            widget: "select"
            multiple: true
            min: 1
            required: true
            hint: "Min 1 **mohon pilih sesuai dengan nama penulis!**"
            options: ["husen", "contributors", "ai"]
            i18n: duplicate
      - label: "Posts content"
        name: "body"
        widget: "markdown"
        required: true
        hint: "Article content"
        i18n: true
        
  - name: authors
    icon: article_person
    label: Authors
    label_singular: "Authors"
    folder: content/author
    media_folder: static/uploads/author
    public_folder: /uploads/author
    create: false
    delete: false
    i18n: true
    path: "{{slug}}/index"
    extension: "md"
    format: "toml-frontmatter"
    slug: "{{slug}}"
    editor:
      preview: false
    thumbnail: "*.profile_image"
    summary: "{{title}}"
    sortable_fields:
      fields: [title, date]
      default:
        field: date
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: duplicate
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
        i18n: true
      - label: "Profile Image"
        name: "extra"
        widget: "object"
        collapsed: false
        summary: "Profile Image"
        i18n: true
        fields:
          - label: "Profile Image"
            name: "profile_image"
            widget: "image"
            required: true
            choose_url: false
            allow_multiple: false
            i18n: duplicate
```
1. Create a new entry
2. Select some values in the select widget
3. Enable the language you want to translate
4. The values in the select widget are not duplicated in the language entry that you want to translate

default locale 
![Image](https://github.com/user-attachments/assets/86f64f7d-223b-42a7-9a2d-f176583c0d6f)

translated content
![Image](https://github.com/user-attachments/assets/c610c67e-dd1a-48d1-97bc-f1e216cd854f)

output translated content
![Image](https://github.com/user-attachments/assets/f335fd0a-142a-49bc-bd73-5fb3f5f3cb3f)
