### ISSUE TITLE
Files config results in an error

### ISSUE THREAD

**Issue by ghostdevv** [sveltia/sveltia-cms#49]
Here is the config:

```yaml
media_folder: "static/uploads/images"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Requests"
        name: "requests"
        file: "src/content/requests.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
```

Seems like the error is coming from here with `otherNames` receiving `[undefined]`.

https://github.com/sveltia/sveltia-cms/blob/b0285df84b18304014202d1ed2016ca4df809685/src/lib/services/utils/files.js#L191

The exact error message is:
![image](https://github.com/sveltia/sveltia-cms/assets/47755378/a05363a6-b07b-4333-a5e2-274d0add58b6)
