### ISSUE TITLE
Any way to filter/group by date past or future?

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#53]
I have events, that dependent on their date get displayed as upcoming events, or as "highlights" with additional videos, images, comments.
I would like to easily be able to filter/group for this, to easily edit only future or only past events.

Maybe the filter/group-option could provide "current time/date(day,month,year)"-"template tags", and to compare two/multiple values.

```
    view_filters:
      - label: 'upcoming Events'
        field: datetime
        greater: '{{currentDate}}'
      - label: 'Highlights'
        field: datetime
        lower: '{{currentDate}}'
```

```
    view_groups:
      - label: "upcoming?"
        field: datetime
        compare: '{{currentDate}}'
```
