### ISSUE TITLE
If `widget: object` is optional, it can't be saved empty if containing required fields

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#55]
```
      - name: "audio"
        label: "Audio"
        widget: object
        required: false
        collapsed: true
        fields:
          - { name: "src", label: "Source-URL", widget: "string" }
          - { name: "url", label: "Webpage-URL", widget: "string" }
          - { name: "img", label: "Image", widget: image, required: false }
          - { name: "descr", label: "Description", widget: "string", required: false }
```
`src` & `url` have to be set.

You should be able to save, if an optional object is empty
