### ISSUE TITLE
Pre-existing images not displayed in gallery

### ISSUE THREAD

**Issue by dsgibbons** [sveltia/sveltia-cms#57]
First of all, thank you for making this. I much prefer using this to Decap CMS.

I have a gallery configured like so in `config.yml`:

```yaml
collections: # A list of collections the CMS should be able to edit
  - name: 'myGallery' 
    label: 'My Gallery'
    folder: 'src/routes/myGallery'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - label: 'Gallery'
        name: 'galleryImages'
        widget: 'list'
        summary: '{{fields.image}}'
        field: { label: Image, name: image, widget: image }
```

When I go to the UI, pre-existing images don't appear in the gallery, even though they are in the Markdown metadata under `galleryImages`. If I re-add the images via Svelta CMS, the images appear in the UI. However, the resulting Markdown is unchanged, and if I reload the post in the UI, the images disappear again.
