### ISSUE TITLE
`summary` ignored for `object` in `list` using `types`

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#62]
```
- name: "components"
  label: "Components"
  label_singular: "Component"
  widget: list
  collapsed: true
  summary: "{{fields.text}}" //gets used for all types
  types:
  - name: "text"
    label: "Text"
    widget: object
    collapsed: true
    summary: "{{fields.text}}" //gets ignored (regardless of "list-summary")
    fields:
    - { name: "group", label: "Group", widget: "number", default: "0", hint: "Grouping of components" }
    - { name: "top", label: "Top", widget: number, default: "0", hint: "Top-offset (-48 to unset row-gap)" }
    - { name: "column_count", label: "columnCount", widget: number, default: "1", hint: "Number of columns text should be in." }
    - { label: "Text", label_singular: "Text", name: "text", widget: markdown }
```

I have to show different summaries based on the type of content. (text, image, ...)
