### ISSUE TITLE
value in summary 0 -> ''

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#64]
https://github.com/sveltia/sveltia-cms/commit/2316f2097995a8df8f6a6280fa34ab6cec8d3327#r130080114

also i have problems accessing a list with variable types for the summary of its containing object...

**Comment by kyoshino** [comment]
Checking...

**Comment by kyoshino** [comment]
> also i have problems accessing a list with variable types for the summary of its containing object...

Do you have an example for this?

**Comment by frankbits** [comment]
```
                      - name: "table"
                        label: "Table"
                        widget: object
                        collapsed: true
#                        summary: "Content: {{fields.content[0].order}}"
                        fields:
                          - { name: "group", label: "Group", widget: "number", default: "0", hint: "Grouping of components" }
                          - { name: "top", label: "Top", widget: number, default: "0", hint: "Top-offset (-48 to unset row-gap)" }
                          - name: "content"
                            label: "Content"
                            widget: list
                            collapsed: true
                            summary: "Order: {{fields.order}}"
                            max: 1
                            types:
                              - name: events
                                label: Events
                                widget: object
                                collapsed: true
                                fields:
                                  #- { name: "only_active", label: "Only active elements?", widget: boolean, default: true }
                                  - name: "order"
                                    label: "Order"
                                    widget: select
                                    options:
                                      - { label: "Ascending", value: "ascending" }
                                      - { label: "Descending", value: "descending" }
                                    default: "ascending"
                                  - { name: "order_by", label: "Order by", widget: "hidden", default: "datetime" }
                                  - name: events
                                    label: Events
                                    widget: list
                                    collapsed: true
                                    hint: If no events are selected, all events are shown.
                                    fields:
                                      - { name: "event", label: "Event", widget: relation, collection: "events", value_field: "{{slug}}", display_fields: [ "title" ] }
                              - name: press
                                label: Press
                                widget: object
                                collapsed: true
                                fields:
                                  - name: "order"
                                    label: "Order"
                                    widget: select
                                    options:
                                      - { label: "Ascending", value: "ascending" }
                                      - { label: "Descending", value: "descending" }
                                    default: "ascending"
                                  - { name: "order_by", label: "Order by", widget: "hidden", default: "date" }
                                  - name: press
                                    label: Press
                                    widget: list
                                    collapsed: true
                                    hint: If no press-articles are selected, all are shown.
                                    fields:
                                      - { name: "press", label: "Press", widget: relation, collection: "press", value_field: "{{slug}}", display_fields: [ "title" ] }
```

I'd like for the summary of table to show the type(s) of added elements (event/press)
The commented line 5 is the last of different tries to access a value of the list-content.
