### ISSUE TITLE
Mdx files not being recognized

### ISSUE THREAD

**Issue by zanhk** [sveltia/sveltia-cms#79]
### Sveltia info

Sveltia 0.8.4

### Problem

In decap cms when I set the options

```
format: "frontmatter"
extension: "mdx"
```

I m able to see mdx files as well

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/eb434ac1-100c-4776-8977-0259e0ed5919)

With Sveltia instead I don't see any post

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/769a8953-7a4f-4680-8046-a79975a8cd61)

If I create a new post from the ui I immediatly see the post after being created

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/134bca61-bf9a-4126-b5dd-572fb82f6624)

And it create the correct files

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/96313bcb-ea0e-4b52-94d7-3a5e72069cbb)

But after clearing the cache and refreshing the page the post disappear

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/d910f4f2-e34b-4691-9e99-4726bd814e4a)

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/c79795fe-9d34-476f-a2f2-33b782826ee3)

Repo: https://github.com/zankhq/astro-starter

### What's the expected result?

To see post with mdx extension

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by kyoshino** [comment]
Because `mdx` is not a supported extension. Not sure why those files are displayed in Decap CMS, but MDX files are not supported anyway. See:

- https://decapcms.org/docs/configuration-options/#extension-and-format
- https://github.com/decaporg/decap-cms/issues/1776
- https://github.com/decaporg/decap-cms/issues/2064

**Comment by zanhk** [comment]
Ok

**Comment by deployn** [comment]
They are recognized:

My config.yml:
```
[...]
collections:
    - name: "posts"
      i18n: true
      label: "Blog Posts"
      folder: "src/content/blog"
      media_folder: "/src/assets/images/blog"
      public_folder: "@assets/images/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Description"
            name: "description"
            widget: "string"
            i18n: true
          - label: "Publish Date"
            name: "pubDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Image"
            name: "heroImage"
            widget: "image"
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
    - name: "posts mdx"
      i18n: true
      label: "Blog Posts MDX"
      folder: "src/content/blog"
      media_folder: "/src/assets/images/blog"
      public_folder: "@assets/images/blog"
      format: "frontmatter"
      extension: "mdx"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Description"
            name: "description"
            widget: "string"
            i18n: true
          - label: "Publish Date"
            name: "pubDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Image"
            name: "heroImage"
            widget: "image"
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
```

My content:
![image](https://github.com/sveltia/sveltia-cms/assets/54767886/7acbc9b5-6459-40ac-b480-953cbb9a3894)

Result:
![image](https://github.com/sveltia/sveltia-cms/assets/54767886/7f34fdf5-2912-4f6d-a20e-aaa2a54dd325)
