### ISSUE TITLE
Adding object section reset other fields

### ISSUE THREAD

**Issue by zanhk** [sveltia/sveltia-cms#83]
Sveltai version: **0.9.1**

With the "object" widget when I click on "add {object}" button it reset the other fields
 
[google_screen_recording_2023-12-09T12-52_45.338Z.webm](https://github.com/sveltia/sveltia-cms/assets/17980844/640695ce-05ed-457e-9586-af95f157ee2b)

sample config used:

```yaml
collections:
    - name: "pages"
      icon: Description
      label: "Pages"
      files:
          - label: "Home Page"
            name: "home"
            file: "src/content/pages/home.json"
            extension: "json"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Description, name: description, widget: markdown }
                - label: Tags
                  name: tags
                  required: false
                  widget: list
                - label: "Hero"
                  name: hero
                  widget: object
                  required: false
                  collapsed: false
                  fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Title 2", name: "title2", widget: "string" }
                      - { label: "Title 3", name: "title3", widget: "string" }
                      - { label: "Title 4", name: "title4", widget: "string" }
                      - { label: "Title 5", name: "title5", widget: "string" }
```

Also seem like that if `required: true` is specified on the widget object I don't see the fields

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/6d18732e-28d2-4037-b4d1-427d53f0279c)

```yaml
- label: "Hero"
  name: hero
  widget: object
  required: true
  collapsed: false
  fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title 2", name: "title2", widget: "string" }
      - { label: "Title 3", name: "title3", widget: "string" }
      - { label: "Title 4", name: "title4", widget: "string" }
      - { label: "Title 5", name: "title5", widget: "string" }
```

Did I missed something on the configuration?

**Comment by kyoshino** [comment]
Hmm, will take a look today 😶

**Comment by kyoshino** [comment]
The fix for the resetting issue is in 🙇🏼 Later I’ll add automated tests to avoid this kind of regressions.

Couldn’t reproduce the empty object. When I just flip `required: false` to `true`, or just remove the line, it just works normally 🤔

**Comment by zanhk** [comment]
Awesome!


For the required problem seem like that the problem happen only when I specify the filename in the file prop:

```yaml
collections:
    - name: "pages"
      icon: Description
      label: "Pages"
      files:
          - label: "Home Page"
            name: "home"
            file: "src/content/pages/home.json" <--------- Here i specified home.json
            extension: "json"
            fields:
                - label: Title
                  name: title
                  widget: string
                - label: Description
                  name: description
                  widget: markdown
                - label: Tags
                  name: tags
                  required: false
                  widget: list
                - label: "Hero"
                  name: hero
                  widget: object
                  required: true
                  collapsed: false
                  fields:
                      - { label: "Title", name: "title", required: true, widget: "string" }
                      - { label: "Title 2", name: "title2", required: true, widget: "string" }
                      - { label: "Title 3", name: "title3", required: true, widget: "string" }
                      - { label: "Title 4", name: "title4", required: true, widget: "string" }
                      - { label: "Title 5", name: "title5", required: true, widget: "string" }
```


![image](https://github.com/sveltia/sveltia-cms/assets/17980844/f9836517-644b-4fea-9b8a-8b4ae024f2d5)


Without specifing it show the fields correctly but it gives an error when trying to save (rightly)


```yaml
collections:
    - name: "pages"
      icon: Description
      label: "Pages"
      files:
          - label: "Home Page"
            name: "home"
            file: "src/content/pages" <------ I didn't specified the filename in the path
            extension: "json"
            fields:
                - label: Title
                  name: title
                  widget: string
                - label: Description
                  name: description
                  widget: markdown
                - label: Tags
                  name: tags
                  required: false
                  widget: list
                - label: "Hero"
                  name: hero
                  widget: object
                  required: true
                  collapsed: false
                  fields:
                      - { label: "Title", name: "title", required: true, widget: "string" }
                      - { label: "Title 2", name: "title2", required: true, widget: "string" }
                      - { label: "Title 3", name: "title3", required: true, widget: "string" }
                      - { label: "Title 4", name: "title4", required: true, widget: "string" }
                      - { label: "Title 5", name: "title5", required: true, widget: "string" }
```

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/c9a1e6aa-1b22-4a24-aebe-e741af50a4a3)

![image](https://github.com/sveltia/sveltia-cms/assets/17980844/27d83468-3749-43d4-aa9f-b1acfabb6d92)

**Comment by zanhk** [comment]
```yaml
collections:
    - name: "pages"
      icon: Description
      label: "Pages"
      files:
          - label: "Home Page"
            name: "home"
            file: "src/content/pages/home.md" <----- md extension
            fields:
                - label: Title
                  name: title
                  widget: string
                - label: Description
                  name: description
                  widget: markdown
                - label: Tags
                  name: tags
                  required: false
                  widget: list
                - label: "Hero"
                  name: hero
                  widget: object
                  required: true
                  collapsed: false
                  fields:
                      - { label: "Title", name: "title", required: true, widget: "string" }
                      - { label: "Title 2", name: "title2", required: true, widget: "string" }
                      - { label: "Title 3", name: "title3", required: true, widget: "string" }
                      - { label: "Title 4", name: "title4", required: true, widget: "string" }
                      - { label: "Title 5", name: "title5", required: true, widget: "string" }
```

With md extension seem to work correctly.
