### ISSUE TITLE
if "widget: image" is direct child of "widget: list", the original filename isn't used

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#9]
```
- name: "images"
  label: "Images"
  label_singular: "Image"
  widget: list
  fields:
    - { name: "img", label: "Image", widget: image}
```
In this case the uploaded images get saved as "image-1683526164572.png" for example.
In other cases the original file name get's used to save the uploaded file.
As far as I can tell the only relevant difference would be it being a direct descendant of a list.

**Comment by kyoshino** [comment]
@frankbits Can you elaborate on the steps to reproduce? The file renaming is supposed to happen only if the in-memory file cache is lost for some reason, especially when the browser tab is closed. But maybe I’m missing other cases. 

(I’ll move the entry draft cache to IndexedDB at some point)

**Comment by frankbits** [comment]
I have a pages collection, where i can add different sections. One of them is the image-list (with some additional fields).
When I save an image in this list, the filename is not copied over. 
Maybe it's also important that this list is in a `types:`? 🤔 

```
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    label_singular: "Page" # Used in the UI
    icon: widgets
    folder: "src/content/pages" # The path to the folder where the documents are stored
    media_folder: "/static/assets/pages"
    public_folder: "/assets/pages"
    create: true # Allow users to create new documents in this collection
    #    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "yml" # The file extension searched for and used to save new collection items
    #format: "yml" # Determines how collection files are parsed and saved (inferred from extension)
    slug: "{{route}}"
    preview_path: "{{route}}"
    identifier_field: "route"
    sortable_fields: [ 'route', 'commit_date' ] # TODO: check if commit_date works on deploy
    fields: # The fields for each document
      - { label: "Route", name: "route", widget: string, hint: "route of the page" }
      - name: "header_transparency"
        label: "Header Transparency"
        widget: select
        options:
          - { label: "opaque", value: "opaque" }
          - { label: "transparent at top", value: "transparent_at_top" }
          - { label: "transparent over first section", value: "transparent" }
        default: "transparent at top"
        hint: "Should the Header be opaque or should it be transparent, only at the top of the page or over the full first section?"
      - { name: "resize_wordmark", label: "Resize Wordmark on scroll", widget: boolean, hint: "Should only be activated if 'Header Transparency: transparent over first section'" }
      - name: "sections"
        label: "Sections"
        label_singular: "Section"
        widget: list
        summary: "{{fields.section}}"
        types:
          - name: "section"
            label: "Section"
            widget: object
            summary: "{{fields.section}}"
            fields:
              - { name: "id", label: "Section-ID", widget: string, required: false, hint: "Only used for better Admin-UX (Info about section, HTML-section-id)" }
              - { label: "Color", name: "color", widget: color, allowInput: true }
              - { label: "Background-Color", name: "background-color", widget: color, allowInput: true }
              - name: "components"
                label: "Components"
                label_singular: "Component"
                widget: list
                types:
                  - name: "headline"
                    label: "Headline"
                    widget: object
                    fields:
                      - { name: "headline", label: "Headline", widget: "string" }
                  - name: "text"
                    label: "Text"
                    widget: object
                    fields:
                      - { name: "text", label: "Text", widget: text }
                  - name: "images"
                    label: "Images"
                    widget: object
                    fields:
                      - name: "images"
                        label: "Images"
                        label_singular: "Image"
                        widget: list
                        fields:
                          - { name: "img", label: "Image", widget: image, allow_multiple: true }
                          - name: "position"
                            label: "Position"
                            widget: "select"
                            options:
                              - { label: "Full Section", value: "full" }
                              - { label: "left", value: "left" }
                              - { label: "right", value: "right" }
                          - { name: "opacity", label: "Opacity", widget: "number", value_type: "float", min: 0, max: 1, step: 0.1, default: 1 }
 ...
```
